// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _fir_top_HH_
#define _fir_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dummy_fe.h"
#include "p_fir_2ch_int_cpp_li.h"
#include "dummy_be.h"
#include "fifo_w16_d1_A.h"
#include "fifo_w40_d1_A.h"

namespace ap_rtl {

struct fir_top : public sc_module {
    // Port declarations 18
    sc_in< sc_lv<16> > din_i_V_dout;
    sc_in< sc_logic > din_i_V_empty_n;
    sc_out< sc_logic > din_i_V_read;
    sc_in< sc_lv<16> > din_q_V_dout;
    sc_in< sc_logic > din_q_V_empty_n;
    sc_out< sc_logic > din_q_V_read;
    sc_out< sc_lv<40> > dout_i_V_din;
    sc_in< sc_logic > dout_i_V_full_n;
    sc_out< sc_logic > dout_i_V_write;
    sc_out< sc_lv<40> > dout_q_V_din;
    sc_in< sc_logic > dout_q_V_full_n;
    sc_out< sc_logic > dout_q_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    fir_top(sc_module_name name);
    SC_HAS_PROCESS(fir_top);

    ~fir_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    dummy_fe* dummy_fe_U0;
    p_fir_2ch_int_cpp_li* p_fir_2ch_int_cpp_li_U0;
    dummy_be* dummy_be_U0;
    fifo_w16_d1_A* fir_in_channel_U;
    fifo_w40_d1_A* fir_out_channel_U;
    sc_signal< sc_logic > dummy_fe_U0_ap_start;
    sc_signal< sc_logic > dummy_fe_U0_ap_done;
    sc_signal< sc_logic > dummy_fe_U0_ap_continue;
    sc_signal< sc_logic > dummy_fe_U0_ap_idle;
    sc_signal< sc_logic > dummy_fe_U0_ap_ready;
    sc_signal< sc_logic > dummy_fe_U0_din_i_V_read;
    sc_signal< sc_logic > dummy_fe_U0_din_q_V_read;
    sc_signal< sc_lv<16> > dummy_fe_U0_out_V_din;
    sc_signal< sc_logic > dummy_fe_U0_out_V_write;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_ap_start;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_ap_done;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_ap_continue;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_ap_idle;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_ap_ready;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_fir_in_read;
    sc_signal< sc_lv<40> > p_fir_2ch_int_cpp_li_U0_fir_out_din;
    sc_signal< sc_logic > p_fir_2ch_int_cpp_li_U0_fir_out_write;
    sc_signal< sc_logic > dummy_be_U0_ap_start;
    sc_signal< sc_logic > dummy_be_U0_ap_done;
    sc_signal< sc_logic > dummy_be_U0_ap_continue;
    sc_signal< sc_logic > dummy_be_U0_ap_idle;
    sc_signal< sc_logic > dummy_be_U0_ap_ready;
    sc_signal< sc_logic > dummy_be_U0_in_V_read;
    sc_signal< sc_lv<40> > dummy_be_U0_dout_i_V_din;
    sc_signal< sc_logic > dummy_be_U0_dout_i_V_write;
    sc_signal< sc_lv<40> > dummy_be_U0_dout_q_V_din;
    sc_signal< sc_logic > dummy_be_U0_dout_q_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > fir_in_channel_full_n;
    sc_signal< sc_lv<16> > fir_in_channel_dout;
    sc_signal< sc_logic > fir_in_channel_empty_n;
    sc_signal< sc_logic > fir_out_channel_full_n;
    sc_signal< sc_lv<40> > fir_out_channel_dout;
    sc_signal< sc_logic > fir_out_channel_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<40> ap_const_lv40_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_din_i_V_read();
    void thread_din_q_V_read();
    void thread_dout_i_V_din();
    void thread_dout_i_V_write();
    void thread_dout_q_V_din();
    void thread_dout_q_V_write();
    void thread_dummy_be_U0_ap_continue();
    void thread_dummy_fe_U0_ap_continue();
    void thread_dummy_fe_U0_ap_start();
    void thread_p_fir_2ch_int_cpp_li_U0_ap_continue();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
