// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cordic,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z030sbv485-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.526000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=109,HLS_SYN_LUT=1117}" *)

module cordic (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        theta_V,
        s_V,
        s_V_ap_vld,
        c_V,
        c_V_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] theta_V;
output  [11:0] s_V;
output   s_V_ap_vld;
output  [11:0] c_V;
output   c_V_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_V_ap_vld;
reg c_V_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [11:0] p_Val2_4_2_fu_318_p2;
reg   [11:0] p_Val2_4_2_reg_1188;
wire   [11:0] p_Val2_7_2_fu_324_p2;
reg   [11:0] p_Val2_7_2_reg_1195;
reg   [0:0] tmp_16_reg_1202;
reg   [0:0] tmp_22_reg_1208;
reg   [0:0] tmp_29_reg_1214;
reg   [0:0] tmp_37_reg_1220;
reg   [0:0] tmp_50_reg_1226;
reg   [0:0] tmp_61_reg_1232;
reg   [0:0] tmp_70_reg_1238;
reg   [0:0] tmp_79_reg_1244;
wire   [11:0] p_Val2_4_4_fu_596_p2;
reg   [11:0] p_Val2_4_4_reg_1250;
wire    ap_CS_fsm_state2;
wire   [11:0] p_Val2_7_4_fu_602_p2;
reg   [11:0] p_Val2_7_4_reg_1257;
wire   [11:0] p_Val2_4_6_fu_778_p2;
reg   [11:0] p_Val2_4_6_reg_1264;
wire    ap_CS_fsm_state3;
wire   [11:0] p_Val2_7_6_fu_784_p2;
reg   [11:0] p_Val2_7_6_reg_1271;
wire   [11:0] p_Val2_4_8_fu_976_p2;
reg   [11:0] p_Val2_4_8_reg_1278;
wire    ap_CS_fsm_state4;
wire   [11:0] p_Val2_7_8_fu_982_p2;
reg   [11:0] p_Val2_7_8_reg_1285;
wire    ap_CS_fsm_state5;
wire   [0:0] tmp_1_fu_130_p3;
wire   [11:0] p_Val2_s_fu_146_p2;
wire   [0:0] tmp_13_fu_160_p3;
wire   [0:0] tmp_3_fu_152_p3;
wire   [9:0] mt7_1_fu_184_p3;
wire   [9:0] OP1_V_2_1_fu_176_p3;
wire   [9:0] r_V_1_1_fu_192_p3;
wire   [9:0] p_Val2_4_1_fu_200_p2;
wire   [10:0] tmp_4_cast_cast_fu_168_p3;
wire   [10:0] p_Val2_7_fu_138_p3;
wire   [10:0] p_Val2_7_1_fu_210_p2;
wire   [11:0] p_Val2_10_1_fu_220_p2;
wire   [10:0] OP1_V_cast_fu_234_p1;
wire   [7:0] tmp_fu_244_p4;
wire   [10:0] mt_2_fu_238_p2;
wire   [0:0] tmp_14_fu_226_p3;
wire   [8:0] tmp_4_fu_258_p4;
wire   [8:0] tmp_2_fu_254_p1;
wire   [8:0] tmp_5_fu_268_p3;
wire   [10:0] mt7_2_fu_280_p2;
wire   [8:0] tmp_7_fu_286_p4;
wire   [8:0] tmp_8_fu_296_p4;
wire   [8:0] tmp_10_fu_306_p3;
wire   [11:0] p_Val2_4_1_cast_fu_206_p1;
wire  signed [11:0] tmp_9_fu_314_p1;
wire  signed [11:0] tmp_6_fu_276_p1;
wire  signed [11:0] p_Val2_7_1_cast_fu_216_p1;
wire   [11:0] p_Val2_10_2_fu_330_p2;
wire   [11:0] p_Val2_10_3_fu_344_p2;
wire   [11:0] p_Val2_10_4_fu_358_p2;
wire   [11:0] p_Val2_10_5_fu_372_p2;
wire   [11:0] p_Val2_10_6_fu_386_p2;
wire   [11:0] p_Val2_10_7_fu_400_p2;
wire   [11:0] p_Val2_10_8_fu_414_p2;
wire   [11:0] p_Val2_10_9_fu_428_p2;
wire   [11:0] mt_3_fu_442_p2;
wire   [8:0] tmp_19_fu_456_p4;
wire   [8:0] tmp_11_fu_447_p4;
wire   [8:0] tmp_16_v_fu_466_p3;
wire   [11:0] mt7_3_fu_477_p2;
wire   [8:0] tmp_20_fu_491_p4;
wire   [8:0] tmp_17_fu_482_p4;
wire   [8:0] tmp_22_v_fu_501_p3;
wire  signed [11:0] tmp_12_fu_508_p1;
wire  signed [11:0] tmp_s_fu_473_p1;
wire   [11:0] p_Val2_4_3_fu_512_p2;
wire   [11:0] mt_4_fu_522_p2;
wire   [7:0] tmp_25_fu_538_p4;
wire   [7:0] tmp_23_fu_528_p4;
wire   [7:0] tmp_28_v_fu_548_p3;
wire   [11:0] p_Val2_7_3_fu_517_p2;
wire   [11:0] mt7_4_fu_559_p2;
wire   [7:0] tmp_28_fu_575_p4;
wire   [7:0] tmp_26_fu_565_p4;
wire   [7:0] tmp_34_v_fu_585_p3;
wire  signed [11:0] tmp_18_fu_592_p1;
wire  signed [11:0] tmp_15_fu_555_p1;
wire   [11:0] mt_5_fu_608_p2;
wire   [6:0] tmp_32_fu_622_p4;
wire   [6:0] tmp_31_fu_613_p4;
wire   [6:0] tmp_40_v_fu_632_p3;
wire   [11:0] mt7_5_fu_643_p2;
wire   [6:0] tmp_35_fu_657_p4;
wire   [6:0] tmp_34_fu_648_p4;
wire   [6:0] tmp_46_v_fu_667_p3;
wire  signed [11:0] tmp_24_fu_674_p1;
wire  signed [11:0] tmp_21_fu_639_p1;
wire   [11:0] p_Val2_4_5_fu_678_p2;
wire  signed [12:0] OP1_V_6_cast_fu_688_p1;
wire   [5:0] tmp_38_fu_698_p4;
wire   [12:0] mt_6_fu_692_p2;
wire   [6:0] tmp_41_fu_712_p4;
wire  signed [6:0] tmp_40_fu_708_p1;
wire   [6:0] tmp_43_fu_722_p3;
wire   [11:0] p_Val2_7_5_fu_683_p2;
wire  signed [12:0] OP1_V_2_6_cast_fu_733_p1;
wire   [5:0] tmp_44_fu_743_p4;
wire   [12:0] mt7_6_fu_737_p2;
wire   [6:0] tmp_47_fu_757_p4;
wire  signed [6:0] tmp_46_fu_753_p1;
wire   [6:0] tmp_49_fu_767_p3;
wire  signed [11:0] tmp_30_fu_774_p1;
wire  signed [11:0] tmp_27_fu_729_p1;
wire  signed [12:0] OP1_V_7_cast_fu_790_p1;
wire   [4:0] tmp_52_fu_799_p4;
wire   [12:0] mt_7_fu_793_p2;
wire   [5:0] tmp_55_fu_812_p4;
wire  signed [5:0] tmp_53_fu_808_p1;
wire   [5:0] tmp_56_fu_822_p3;
wire  signed [12:0] OP1_V_2_7_cast_fu_833_p1;
wire   [4:0] tmp_57_fu_842_p4;
wire   [12:0] mt7_7_fu_836_p2;
wire   [5:0] tmp_59_fu_855_p4;
wire  signed [5:0] tmp_58_fu_851_p1;
wire   [5:0] tmp_60_fu_865_p3;
wire  signed [11:0] tmp_36_fu_872_p1;
wire  signed [11:0] tmp_33_fu_829_p1;
wire   [11:0] p_Val2_4_7_fu_876_p2;
wire  signed [12:0] OP1_V_8_cast_fu_886_p1;
wire   [3:0] tmp_62_fu_896_p4;
wire   [12:0] mt_8_fu_890_p2;
wire   [4:0] tmp_64_fu_910_p4;
wire  signed [4:0] tmp_63_fu_906_p1;
wire   [4:0] tmp_65_fu_920_p3;
wire   [11:0] p_Val2_7_7_fu_881_p2;
wire  signed [12:0] OP1_V_2_8_cast_fu_931_p1;
wire   [3:0] tmp_66_fu_941_p4;
wire   [12:0] mt7_8_fu_935_p2;
wire   [4:0] tmp_68_fu_955_p4;
wire  signed [4:0] tmp_67_fu_951_p1;
wire   [4:0] tmp_69_fu_965_p3;
wire  signed [11:0] tmp_42_fu_972_p1;
wire  signed [11:0] tmp_39_fu_927_p1;
wire  signed [12:0] OP1_V_9_cast_fu_988_p1;
wire   [2:0] tmp_71_fu_997_p4;
wire   [12:0] mt_9_fu_991_p2;
wire   [3:0] tmp_73_fu_1010_p4;
wire  signed [3:0] tmp_72_fu_1006_p1;
wire   [3:0] tmp_74_fu_1020_p3;
wire  signed [12:0] OP1_V_2_9_cast_fu_1031_p1;
wire   [2:0] tmp_75_fu_1040_p4;
wire   [12:0] mt7_9_fu_1034_p2;
wire   [3:0] tmp_77_fu_1053_p4;
wire  signed [3:0] tmp_76_fu_1049_p1;
wire   [3:0] tmp_78_fu_1063_p3;
wire  signed [11:0] tmp_48_fu_1070_p1;
wire  signed [11:0] tmp_45_fu_1027_p1;
wire   [11:0] p_Val2_4_9_fu_1074_p2;
wire  signed [12:0] OP1_V_2_cast_fu_1084_p1;
wire   [1:0] tmp_80_fu_1094_p4;
wire   [12:0] mt_s_fu_1088_p2;
wire   [2:0] tmp_82_fu_1108_p4;
wire  signed [2:0] tmp_81_fu_1104_p1;
wire   [2:0] tmp_83_fu_1118_p3;
wire   [11:0] p_Val2_7_9_fu_1079_p2;
wire  signed [12:0] OP1_V_2_cast_10_fu_1129_p1;
wire   [1:0] tmp_84_fu_1139_p4;
wire   [12:0] mt7_s_fu_1133_p2;
wire   [2:0] tmp_86_fu_1153_p4;
wire  signed [2:0] tmp_85_fu_1149_p1;
wire   [2:0] tmp_87_fu_1163_p3;
wire  signed [11:0] tmp_54_fu_1170_p1;
wire  signed [11:0] tmp_51_fu_1125_p1;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        p_Val2_4_2_reg_1188 <= p_Val2_4_2_fu_318_p2;
        p_Val2_7_2_reg_1195 <= p_Val2_7_2_fu_324_p2;
        tmp_16_reg_1202 <= p_Val2_10_2_fu_330_p2[32'd11];
        tmp_22_reg_1208 <= p_Val2_10_3_fu_344_p2[32'd11];
        tmp_29_reg_1214 <= p_Val2_10_4_fu_358_p2[32'd11];
        tmp_37_reg_1220 <= p_Val2_10_5_fu_372_p2[32'd11];
        tmp_50_reg_1226 <= p_Val2_10_6_fu_386_p2[32'd11];
        tmp_61_reg_1232 <= p_Val2_10_7_fu_400_p2[32'd11];
        tmp_70_reg_1238 <= p_Val2_10_8_fu_414_p2[32'd11];
        tmp_79_reg_1244 <= p_Val2_10_9_fu_428_p2[32'd11];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        p_Val2_4_4_reg_1250 <= p_Val2_4_4_fu_596_p2;
        p_Val2_7_4_reg_1257 <= p_Val2_7_4_fu_602_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_Val2_4_6_reg_1264 <= p_Val2_4_6_fu_778_p2;
        p_Val2_7_6_reg_1271 <= p_Val2_7_6_fu_784_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        p_Val2_4_8_reg_1278 <= p_Val2_4_8_fu_976_p2;
        p_Val2_7_8_reg_1285 <= p_Val2_7_8_fu_982_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        c_V_ap_vld = 1'b1;
    end else begin
        c_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        s_V_ap_vld = 1'b1;
    end else begin
        s_V_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_2_1_fu_176_p3 = ((tmp_1_fu_130_p3[0:0] === 1'b1) ? 10'd713 : 10'd310);

assign OP1_V_2_6_cast_fu_733_p1 = $signed(p_Val2_7_5_fu_683_p2);

assign OP1_V_2_7_cast_fu_833_p1 = $signed(p_Val2_7_6_reg_1271);

assign OP1_V_2_8_cast_fu_931_p1 = $signed(p_Val2_7_7_fu_881_p2);

assign OP1_V_2_9_cast_fu_1031_p1 = $signed(p_Val2_7_8_reg_1285);

assign OP1_V_2_cast_10_fu_1129_p1 = $signed(p_Val2_7_9_fu_1079_p2);

assign OP1_V_2_cast_fu_1084_p1 = $signed(p_Val2_4_9_fu_1074_p2);

assign OP1_V_6_cast_fu_688_p1 = $signed(p_Val2_4_5_fu_678_p2);

assign OP1_V_7_cast_fu_790_p1 = $signed(p_Val2_4_6_reg_1264);

assign OP1_V_8_cast_fu_886_p1 = $signed(p_Val2_4_7_fu_876_p2);

assign OP1_V_9_cast_fu_988_p1 = $signed(p_Val2_4_8_reg_1278);

assign OP1_V_cast_fu_234_p1 = p_Val2_4_1_fu_200_p2;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign c_V = ($signed(p_Val2_4_9_fu_1074_p2) - $signed(tmp_54_fu_1170_p1));

assign mt7_1_fu_184_p3 = ((tmp_1_fu_130_p3[0:0] === 1'b1) ? 10'd310 : 10'd713);

assign mt7_2_fu_280_p2 = (11'd0 - p_Val2_7_1_fu_210_p2);

assign mt7_3_fu_477_p2 = (12'd0 - p_Val2_7_2_reg_1195);

assign mt7_4_fu_559_p2 = (12'd0 - p_Val2_7_3_fu_517_p2);

assign mt7_5_fu_643_p2 = (12'd0 - p_Val2_7_4_reg_1257);

assign mt7_6_fu_737_p2 = ($signed(13'd0) - $signed(OP1_V_2_6_cast_fu_733_p1));

assign mt7_7_fu_836_p2 = ($signed(13'd0) - $signed(OP1_V_2_7_cast_fu_833_p1));

assign mt7_8_fu_935_p2 = ($signed(13'd0) - $signed(OP1_V_2_8_cast_fu_931_p1));

assign mt7_9_fu_1034_p2 = ($signed(13'd0) - $signed(OP1_V_2_9_cast_fu_1031_p1));

assign mt7_s_fu_1133_p2 = ($signed(13'd0) - $signed(OP1_V_2_cast_10_fu_1129_p1));

assign mt_2_fu_238_p2 = (11'd0 - OP1_V_cast_fu_234_p1);

assign mt_3_fu_442_p2 = (12'd0 - p_Val2_4_2_reg_1188);

assign mt_4_fu_522_p2 = (12'd0 - p_Val2_4_3_fu_512_p2);

assign mt_5_fu_608_p2 = (12'd0 - p_Val2_4_4_reg_1250);

assign mt_6_fu_692_p2 = ($signed(13'd0) - $signed(OP1_V_6_cast_fu_688_p1));

assign mt_7_fu_793_p2 = ($signed(13'd0) - $signed(OP1_V_7_cast_fu_790_p1));

assign mt_8_fu_890_p2 = ($signed(13'd0) - $signed(OP1_V_8_cast_fu_886_p1));

assign mt_9_fu_991_p2 = ($signed(13'd0) - $signed(OP1_V_9_cast_fu_988_p1));

assign mt_s_fu_1088_p2 = ($signed(13'd0) - $signed(OP1_V_2_cast_fu_1084_p1));

assign p_Val2_10_1_fu_220_p2 = ($signed(theta_V) + $signed(12'd2818));

assign p_Val2_10_2_fu_330_p2 = ($signed(theta_V) + $signed(12'd2568));

assign p_Val2_10_3_fu_344_p2 = ($signed(theta_V) + $signed(12'd2441));

assign p_Val2_10_4_fu_358_p2 = ($signed(theta_V) + $signed(12'd2378));

assign p_Val2_10_5_fu_372_p2 = ($signed(theta_V) + $signed(12'd2347));

assign p_Val2_10_6_fu_386_p2 = ($signed(theta_V) + $signed(12'd2332));

assign p_Val2_10_7_fu_400_p2 = ($signed(theta_V) + $signed(12'd2325));

assign p_Val2_10_8_fu_414_p2 = ($signed(theta_V) + $signed(12'd2322));

assign p_Val2_10_9_fu_428_p2 = ($signed(theta_V) + $signed(12'd2321));

assign p_Val2_4_1_cast_fu_206_p1 = p_Val2_4_1_fu_200_p2;

assign p_Val2_4_1_fu_200_p2 = ($signed(10'd621) - $signed(r_V_1_1_fu_192_p3));

assign p_Val2_4_2_fu_318_p2 = ($signed(p_Val2_4_1_cast_fu_206_p1) - $signed(tmp_9_fu_314_p1));

assign p_Val2_4_3_fu_512_p2 = ($signed(p_Val2_4_2_reg_1188) - $signed(tmp_12_fu_508_p1));

assign p_Val2_4_4_fu_596_p2 = ($signed(p_Val2_4_3_fu_512_p2) - $signed(tmp_18_fu_592_p1));

assign p_Val2_4_5_fu_678_p2 = ($signed(p_Val2_4_4_reg_1250) - $signed(tmp_24_fu_674_p1));

assign p_Val2_4_6_fu_778_p2 = ($signed(p_Val2_4_5_fu_678_p2) - $signed(tmp_30_fu_774_p1));

assign p_Val2_4_7_fu_876_p2 = ($signed(p_Val2_4_6_reg_1264) - $signed(tmp_36_fu_872_p1));

assign p_Val2_4_8_fu_976_p2 = ($signed(p_Val2_4_7_fu_876_p2) - $signed(tmp_42_fu_972_p1));

assign p_Val2_4_9_fu_1074_p2 = ($signed(p_Val2_4_8_reg_1278) - $signed(tmp_48_fu_1070_p1));

assign p_Val2_7_1_cast_fu_216_p1 = $signed(p_Val2_7_1_fu_210_p2);

assign p_Val2_7_1_fu_210_p2 = (tmp_4_cast_cast_fu_168_p3 + p_Val2_7_fu_138_p3);

assign p_Val2_7_2_fu_324_p2 = ($signed(tmp_6_fu_276_p1) + $signed(p_Val2_7_1_cast_fu_216_p1));

assign p_Val2_7_3_fu_517_p2 = ($signed(tmp_s_fu_473_p1) + $signed(p_Val2_7_2_reg_1195));

assign p_Val2_7_4_fu_602_p2 = ($signed(tmp_15_fu_555_p1) + $signed(p_Val2_7_3_fu_517_p2));

assign p_Val2_7_5_fu_683_p2 = ($signed(tmp_21_fu_639_p1) + $signed(p_Val2_7_4_reg_1257));

assign p_Val2_7_6_fu_784_p2 = ($signed(tmp_27_fu_729_p1) + $signed(p_Val2_7_5_fu_683_p2));

assign p_Val2_7_7_fu_881_p2 = ($signed(tmp_33_fu_829_p1) + $signed(p_Val2_7_6_reg_1271));

assign p_Val2_7_8_fu_982_p2 = ($signed(tmp_39_fu_927_p1) + $signed(p_Val2_7_7_fu_881_p2));

assign p_Val2_7_9_fu_1079_p2 = ($signed(tmp_45_fu_1027_p1) + $signed(p_Val2_7_8_reg_1285));

assign p_Val2_7_fu_138_p3 = ((tmp_1_fu_130_p3[0:0] === 1'b1) ? 11'd1427 : 11'd621);

assign p_Val2_s_fu_146_p2 = ($signed(theta_V) + $signed(12'd3292));

assign r_V_1_1_fu_192_p3 = ((tmp_3_fu_152_p3[0:0] === 1'b1) ? mt7_1_fu_184_p3 : OP1_V_2_1_fu_176_p3);

assign s_V = ($signed(tmp_51_fu_1125_p1) + $signed(p_Val2_7_9_fu_1079_p2));

assign tmp_10_fu_306_p3 = ((tmp_14_fu_226_p3[0:0] === 1'b1) ? tmp_7_fu_286_p4 : tmp_8_fu_296_p4);

assign tmp_11_fu_447_p4 = {{p_Val2_4_2_reg_1188[11:3]}};

assign tmp_12_fu_508_p1 = $signed(tmp_22_v_fu_501_p3);

assign tmp_13_fu_160_p3 = p_Val2_s_fu_146_p2[32'd11];

assign tmp_14_fu_226_p3 = p_Val2_10_1_fu_220_p2[32'd11];

assign tmp_15_fu_555_p1 = $signed(tmp_28_v_fu_548_p3);

assign tmp_16_v_fu_466_p3 = ((tmp_16_reg_1202[0:0] === 1'b1) ? tmp_19_fu_456_p4 : tmp_11_fu_447_p4);

assign tmp_17_fu_482_p4 = {{p_Val2_7_2_reg_1195[11:3]}};

assign tmp_18_fu_592_p1 = $signed(tmp_34_v_fu_585_p3);

assign tmp_19_fu_456_p4 = {{mt_3_fu_442_p2[11:3]}};

assign tmp_1_fu_130_p3 = theta_V[32'd11];

assign tmp_20_fu_491_p4 = {{mt7_3_fu_477_p2[11:3]}};

assign tmp_21_fu_639_p1 = $signed(tmp_40_v_fu_632_p3);

assign tmp_22_v_fu_501_p3 = ((tmp_16_reg_1202[0:0] === 1'b1) ? tmp_20_fu_491_p4 : tmp_17_fu_482_p4);

assign tmp_23_fu_528_p4 = {{p_Val2_4_3_fu_512_p2[11:4]}};

assign tmp_24_fu_674_p1 = $signed(tmp_46_v_fu_667_p3);

assign tmp_25_fu_538_p4 = {{mt_4_fu_522_p2[11:4]}};

assign tmp_26_fu_565_p4 = {{p_Val2_7_3_fu_517_p2[11:4]}};

assign tmp_27_fu_729_p1 = $signed(tmp_43_fu_722_p3);

assign tmp_28_fu_575_p4 = {{mt7_4_fu_559_p2[11:4]}};

assign tmp_28_v_fu_548_p3 = ((tmp_22_reg_1208[0:0] === 1'b1) ? tmp_25_fu_538_p4 : tmp_23_fu_528_p4);

assign tmp_2_fu_254_p1 = tmp_fu_244_p4;

assign tmp_30_fu_774_p1 = $signed(tmp_49_fu_767_p3);

assign tmp_31_fu_613_p4 = {{p_Val2_4_4_reg_1250[11:5]}};

assign tmp_32_fu_622_p4 = {{mt_5_fu_608_p2[11:5]}};

assign tmp_33_fu_829_p1 = $signed(tmp_56_fu_822_p3);

assign tmp_34_fu_648_p4 = {{p_Val2_7_4_reg_1257[11:5]}};

assign tmp_34_v_fu_585_p3 = ((tmp_22_reg_1208[0:0] === 1'b1) ? tmp_28_fu_575_p4 : tmp_26_fu_565_p4);

assign tmp_35_fu_657_p4 = {{mt7_5_fu_643_p2[11:5]}};

assign tmp_36_fu_872_p1 = $signed(tmp_60_fu_865_p3);

assign tmp_38_fu_698_p4 = {{p_Val2_4_5_fu_678_p2[11:6]}};

assign tmp_39_fu_927_p1 = $signed(tmp_65_fu_920_p3);

assign tmp_3_fu_152_p3 = p_Val2_s_fu_146_p2[32'd11];

assign tmp_40_fu_708_p1 = $signed(tmp_38_fu_698_p4);

assign tmp_40_v_fu_632_p3 = ((tmp_29_reg_1214[0:0] === 1'b1) ? tmp_32_fu_622_p4 : tmp_31_fu_613_p4);

assign tmp_41_fu_712_p4 = {{mt_6_fu_692_p2[12:6]}};

assign tmp_42_fu_972_p1 = $signed(tmp_69_fu_965_p3);

assign tmp_43_fu_722_p3 = ((tmp_37_reg_1220[0:0] === 1'b1) ? tmp_41_fu_712_p4 : tmp_40_fu_708_p1);

assign tmp_44_fu_743_p4 = {{p_Val2_7_5_fu_683_p2[11:6]}};

assign tmp_45_fu_1027_p1 = $signed(tmp_74_fu_1020_p3);

assign tmp_46_fu_753_p1 = $signed(tmp_44_fu_743_p4);

assign tmp_46_v_fu_667_p3 = ((tmp_29_reg_1214[0:0] === 1'b1) ? tmp_35_fu_657_p4 : tmp_34_fu_648_p4);

assign tmp_47_fu_757_p4 = {{mt7_6_fu_737_p2[12:6]}};

assign tmp_48_fu_1070_p1 = $signed(tmp_78_fu_1063_p3);

assign tmp_49_fu_767_p3 = ((tmp_37_reg_1220[0:0] === 1'b1) ? tmp_47_fu_757_p4 : tmp_46_fu_753_p1);

assign tmp_4_cast_cast_fu_168_p3 = ((tmp_13_fu_160_p3[0:0] === 1'b1) ? 11'd1737 : 11'd310);

assign tmp_4_fu_258_p4 = {{mt_2_fu_238_p2[10:2]}};

assign tmp_51_fu_1125_p1 = $signed(tmp_83_fu_1118_p3);

assign tmp_52_fu_799_p4 = {{p_Val2_4_6_reg_1264[11:7]}};

assign tmp_53_fu_808_p1 = $signed(tmp_52_fu_799_p4);

assign tmp_54_fu_1170_p1 = $signed(tmp_87_fu_1163_p3);

assign tmp_55_fu_812_p4 = {{mt_7_fu_793_p2[12:7]}};

assign tmp_56_fu_822_p3 = ((tmp_50_reg_1226[0:0] === 1'b1) ? tmp_55_fu_812_p4 : tmp_53_fu_808_p1);

assign tmp_57_fu_842_p4 = {{p_Val2_7_6_reg_1271[11:7]}};

assign tmp_58_fu_851_p1 = $signed(tmp_57_fu_842_p4);

assign tmp_59_fu_855_p4 = {{mt7_7_fu_836_p2[12:7]}};

assign tmp_5_fu_268_p3 = ((tmp_14_fu_226_p3[0:0] === 1'b1) ? tmp_4_fu_258_p4 : tmp_2_fu_254_p1);

assign tmp_60_fu_865_p3 = ((tmp_50_reg_1226[0:0] === 1'b1) ? tmp_59_fu_855_p4 : tmp_58_fu_851_p1);

assign tmp_62_fu_896_p4 = {{p_Val2_4_7_fu_876_p2[11:8]}};

assign tmp_63_fu_906_p1 = $signed(tmp_62_fu_896_p4);

assign tmp_64_fu_910_p4 = {{mt_8_fu_890_p2[12:8]}};

assign tmp_65_fu_920_p3 = ((tmp_61_reg_1232[0:0] === 1'b1) ? tmp_64_fu_910_p4 : tmp_63_fu_906_p1);

assign tmp_66_fu_941_p4 = {{p_Val2_7_7_fu_881_p2[11:8]}};

assign tmp_67_fu_951_p1 = $signed(tmp_66_fu_941_p4);

assign tmp_68_fu_955_p4 = {{mt7_8_fu_935_p2[12:8]}};

assign tmp_69_fu_965_p3 = ((tmp_61_reg_1232[0:0] === 1'b1) ? tmp_68_fu_955_p4 : tmp_67_fu_951_p1);

assign tmp_6_fu_276_p1 = $signed(tmp_5_fu_268_p3);

assign tmp_71_fu_997_p4 = {{p_Val2_4_8_reg_1278[11:9]}};

assign tmp_72_fu_1006_p1 = $signed(tmp_71_fu_997_p4);

assign tmp_73_fu_1010_p4 = {{mt_9_fu_991_p2[12:9]}};

assign tmp_74_fu_1020_p3 = ((tmp_70_reg_1238[0:0] === 1'b1) ? tmp_73_fu_1010_p4 : tmp_72_fu_1006_p1);

assign tmp_75_fu_1040_p4 = {{p_Val2_7_8_reg_1285[11:9]}};

assign tmp_76_fu_1049_p1 = $signed(tmp_75_fu_1040_p4);

assign tmp_77_fu_1053_p4 = {{mt7_9_fu_1034_p2[12:9]}};

assign tmp_78_fu_1063_p3 = ((tmp_70_reg_1238[0:0] === 1'b1) ? tmp_77_fu_1053_p4 : tmp_76_fu_1049_p1);

assign tmp_7_fu_286_p4 = {{mt7_2_fu_280_p2[10:2]}};

assign tmp_80_fu_1094_p4 = {{p_Val2_4_9_fu_1074_p2[11:10]}};

assign tmp_81_fu_1104_p1 = $signed(tmp_80_fu_1094_p4);

assign tmp_82_fu_1108_p4 = {{mt_s_fu_1088_p2[12:10]}};

assign tmp_83_fu_1118_p3 = ((tmp_79_reg_1244[0:0] === 1'b1) ? tmp_82_fu_1108_p4 : tmp_81_fu_1104_p1);

assign tmp_84_fu_1139_p4 = {{p_Val2_7_9_fu_1079_p2[11:10]}};

assign tmp_85_fu_1149_p1 = $signed(tmp_84_fu_1139_p4);

assign tmp_86_fu_1153_p4 = {{mt7_s_fu_1133_p2[12:10]}};

assign tmp_87_fu_1163_p3 = ((tmp_79_reg_1244[0:0] === 1'b1) ? tmp_86_fu_1153_p4 : tmp_85_fu_1149_p1);

assign tmp_8_fu_296_p4 = {{p_Val2_7_1_fu_210_p2[10:2]}};

assign tmp_9_fu_314_p1 = $signed(tmp_10_fu_306_p3);

assign tmp_fu_244_p4 = {{p_Val2_4_1_fu_200_p2[9:2]}};

assign tmp_s_fu_473_p1 = $signed(tmp_16_v_fu_466_p3);

endmodule //cordic
