-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4.op
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity pipe3 is
port (
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    out_r : OUT STD_LOGIC_VECTOR (31 downto 0);
    out_r_ap_vld : OUT STD_LOGIC );
end;


architecture behav of pipe3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "pipe3,hls_ip_2017_4_op,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu9p-fsgd2104-3-e-es1,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.388000,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=3,HLS_SYN_FF=0,HLS_SYN_LUT=84}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_35_p0 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_35_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_35_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_fu_41_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_fu_41_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_47_p1 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_done <= ap_start;
    ap_idle <= ap_const_logic_1;
    ap_ready <= ap_start;
    out_r <= std_logic_vector(unsigned(tmp1_fu_41_p2) + unsigned(tmp_2_fu_47_p1));

    out_r_ap_vld_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_1)) then 
            out_r_ap_vld <= ap_const_logic_1;
        else 
            out_r_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_fu_41_p1 <= a;
    tmp1_fu_41_p2 <= std_logic_vector(unsigned(tmp_fu_35_p2) + unsigned(tmp1_fu_41_p1));
    tmp_2_fu_47_p1 <= b;
    tmp_fu_35_p0 <= b;
    tmp_fu_35_p1 <= a;
    tmp_fu_35_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_fu_35_p0) * signed(tmp_fu_35_p1))), 32));
end behav;
