-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dummy_fe is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    din_i_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_i_V_empty_n : IN STD_LOGIC;
    din_i_V_read : OUT STD_LOGIC;
    din_q_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    din_q_V_empty_n : IN STD_LOGIC;
    din_q_V_read : OUT STD_LOGIC;
    out_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    out_V_full_n : IN STD_LOGIC;
    out_V_write : OUT STD_LOGIC );
end;


architecture behav of dummy_fe is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv12_9C4 : STD_LOGIC_VECTOR (11 downto 0) := "100111000100";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal din_i_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_fu_65_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal din_q_V_blk_n : STD_LOGIC;
    signal out_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_2_fu_71_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal i_2_reg_80 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal din_q_V_read_reg_85 : STD_LOGIC_VECTOR (15 downto 0);
    signal i_reg_54 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_reg_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_reg_54 <= i_2_reg_80;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_reg_54 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                din_q_V_read_reg_85 <= din_q_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_2_reg_80 <= i_2_fu_71_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_assign_proc : process(din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, tmp_fu_65_p2)
    begin
                ap_block_state2 <= (((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    din_i_V_blk_n_assign_proc : process(din_i_V_empty_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if (((tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_i_V_blk_n <= din_i_V_empty_n;
        else 
            din_i_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_i_V_read_assign_proc : process(din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_i_V_read <= ap_const_logic_1;
        else 
            din_i_V_read <= ap_const_logic_0;
        end if; 
    end process;


    din_q_V_blk_n_assign_proc : process(din_q_V_empty_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if (((tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_q_V_blk_n <= din_q_V_empty_n;
        else 
            din_q_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    din_q_V_read_assign_proc : process(din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2)
    begin
        if ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            din_q_V_read <= ap_const_logic_1;
        else 
            din_q_V_read <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_71_p2 <= std_logic_vector(unsigned(i_reg_54) + unsigned(ap_const_lv12_1));

    out_V_blk_n_assign_proc : process(out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            out_V_blk_n <= out_V_full_n;
        else 
            out_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_V_din_assign_proc : process(din_i_V_dout, din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2, ap_CS_fsm_state3, din_q_V_read_reg_85)
    begin
        if (((out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            out_V_din <= din_q_V_read_reg_85;
        elsif ((not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            out_V_din <= din_i_V_dout;
        else 
            out_V_din <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    out_V_write_assign_proc : process(din_i_V_empty_n, din_q_V_empty_n, out_V_full_n, ap_CS_fsm_state2, tmp_fu_65_p2, ap_CS_fsm_state3)
    begin
        if ((((out_V_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not((((tmp_fu_65_p2 = ap_const_lv1_0) and (din_q_V_empty_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (out_V_full_n = ap_const_logic_0)) or ((tmp_fu_65_p2 = ap_const_lv1_0) and (din_i_V_empty_n = ap_const_logic_0)))) and (tmp_fu_65_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            out_V_write <= ap_const_logic_1;
        else 
            out_V_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_65_p2 <= "1" when (i_reg_54 = ap_const_lv12_9C4) else "0";
end behav;
