-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity loop_functions is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    A_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    A_ce0 : OUT STD_LOGIC;
    A_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    B_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    B_ce0 : OUT STD_LOGIC;
    B_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
    X_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    X_ce0 : OUT STD_LOGIC;
    X_we0 : OUT STD_LOGIC;
    X_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    Y_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    Y_ce0 : OUT STD_LOGIC;
    Y_we0 : OUT STD_LOGIC;
    Y_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    xlimit : IN STD_LOGIC_VECTOR (4 downto 0);
    ylimit : IN STD_LOGIC_VECTOR (4 downto 0) );
end;


architecture behav of loop_functions is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "loop_functions,hls_ip_2017_4,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=25.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.660250,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=66,HLS_SYN_LUT=193}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_sub_func_fu_34_ap_start : STD_LOGIC;
    signal grp_sub_func_fu_34_ap_done : STD_LOGIC;
    signal grp_sub_func_fu_34_ap_idle : STD_LOGIC;
    signal grp_sub_func_fu_34_ap_ready : STD_LOGIC;
    signal grp_sub_func_fu_34_I_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sub_func_fu_34_I_ce0 : STD_LOGIC;
    signal grp_sub_func_fu_34_O_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sub_func_fu_34_O_ce0 : STD_LOGIC;
    signal grp_sub_func_fu_34_O_we0 : STD_LOGIC;
    signal grp_sub_func_fu_34_O_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_sub_func_fu_44_ap_start : STD_LOGIC;
    signal grp_sub_func_fu_44_ap_done : STD_LOGIC;
    signal grp_sub_func_fu_44_ap_idle : STD_LOGIC;
    signal grp_sub_func_fu_44_ap_ready : STD_LOGIC;
    signal grp_sub_func_fu_44_I_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sub_func_fu_44_I_ce0 : STD_LOGIC;
    signal grp_sub_func_fu_44_O_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_sub_func_fu_44_O_ce0 : STD_LOGIC;
    signal grp_sub_func_fu_44_O_we0 : STD_LOGIC;
    signal grp_sub_func_fu_44_O_d0 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_reg_grp_sub_func_fu_34_ap_start : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_reg_grp_sub_func_fu_44_ap_start : STD_LOGIC := '0';
    signal ap_block_state2_on_subcall_done : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);

    component sub_func IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        I_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        I_ce0 : OUT STD_LOGIC;
        I_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        O_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        O_ce0 : OUT STD_LOGIC;
        O_we0 : OUT STD_LOGIC;
        O_d0 : OUT STD_LOGIC_VECTOR (12 downto 0);
        limit : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    grp_sub_func_fu_34 : component sub_func
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sub_func_fu_34_ap_start,
        ap_done => grp_sub_func_fu_34_ap_done,
        ap_idle => grp_sub_func_fu_34_ap_idle,
        ap_ready => grp_sub_func_fu_34_ap_ready,
        I_address0 => grp_sub_func_fu_34_I_address0,
        I_ce0 => grp_sub_func_fu_34_I_ce0,
        I_q0 => A_q0,
        O_address0 => grp_sub_func_fu_34_O_address0,
        O_ce0 => grp_sub_func_fu_34_O_ce0,
        O_we0 => grp_sub_func_fu_34_O_we0,
        O_d0 => grp_sub_func_fu_34_O_d0,
        limit => xlimit);

    grp_sub_func_fu_44 : component sub_func
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sub_func_fu_44_ap_start,
        ap_done => grp_sub_func_fu_44_ap_done,
        ap_idle => grp_sub_func_fu_44_ap_idle,
        ap_ready => grp_sub_func_fu_44_ap_ready,
        I_address0 => grp_sub_func_fu_44_I_address0,
        I_ce0 => grp_sub_func_fu_44_I_ce0,
        I_q0 => B_q0,
        O_address0 => grp_sub_func_fu_44_O_address0,
        O_ce0 => grp_sub_func_fu_44_O_ce0,
        O_we0 => grp_sub_func_fu_44_O_we0,
        O_d0 => grp_sub_func_fu_44_O_d0,
        limit => ylimit);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_reg_grp_sub_func_fu_34_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_sub_func_fu_34_ap_start <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_sub_func_fu_34_ap_start <= ap_const_logic_1;
                elsif ((grp_sub_func_fu_34_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_sub_func_fu_34_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_reg_grp_sub_func_fu_44_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_reg_grp_sub_func_fu_44_ap_start <= ap_const_logic_0;
            else
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_reg_grp_sub_func_fu_44_ap_start <= ap_const_logic_1;
                elsif ((grp_sub_func_fu_44_ap_ready = ap_const_logic_1)) then 
                    ap_reg_grp_sub_func_fu_44_ap_start <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    A_address0 <= grp_sub_func_fu_34_I_address0;
    A_ce0 <= grp_sub_func_fu_34_I_ce0;
    B_address0 <= grp_sub_func_fu_44_I_address0;
    B_ce0 <= grp_sub_func_fu_44_I_ce0;
    X_address0 <= grp_sub_func_fu_34_O_address0;
    X_ce0 <= grp_sub_func_fu_34_O_ce0;
    X_d0 <= grp_sub_func_fu_34_O_d0;
    X_we0 <= grp_sub_func_fu_34_O_we0;
    Y_address0 <= grp_sub_func_fu_44_O_address0;
    Y_ce0 <= grp_sub_func_fu_44_O_ce0;
    Y_d0 <= grp_sub_func_fu_44_O_d0;
    Y_we0 <= grp_sub_func_fu_44_O_we0;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);

    ap_block_state2_on_subcall_done_assign_proc : process(grp_sub_func_fu_34_ap_done, grp_sub_func_fu_44_ap_done)
    begin
                ap_block_state2_on_subcall_done <= ((grp_sub_func_fu_44_ap_done = ap_const_logic_0) or (grp_sub_func_fu_34_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, ap_block_state2_on_subcall_done)
    begin
        if (((ap_const_boolean_0 = ap_block_state2_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_sub_func_fu_34_ap_start <= ap_reg_grp_sub_func_fu_34_ap_start;
    grp_sub_func_fu_44_ap_start <= ap_reg_grp_sub_func_fu_44_ap_start;
end behav;
