-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cordic is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    theta_V : IN STD_LOGIC_VECTOR (11 downto 0);
    s_V : OUT STD_LOGIC_VECTOR (11 downto 0);
    s_V_ap_vld : OUT STD_LOGIC;
    c_V : OUT STD_LOGIC_VECTOR (11 downto 0);
    c_V_ap_vld : OUT STD_LOGIC );
end;


architecture behav of cordic is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "cordic,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z030sbv485-3,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.526000,HLS_SYN_LAT=4,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=109,HLS_SYN_LUT=1117}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv11_593 : STD_LOGIC_VECTOR (10 downto 0) := "10110010011";
    constant ap_const_lv11_26D : STD_LOGIC_VECTOR (10 downto 0) := "01001101101";
    constant ap_const_lv12_CDC : STD_LOGIC_VECTOR (11 downto 0) := "110011011100";
    constant ap_const_lv11_6C9 : STD_LOGIC_VECTOR (10 downto 0) := "11011001001";
    constant ap_const_lv11_136 : STD_LOGIC_VECTOR (10 downto 0) := "00100110110";
    constant ap_const_lv10_2C9 : STD_LOGIC_VECTOR (9 downto 0) := "1011001001";
    constant ap_const_lv10_136 : STD_LOGIC_VECTOR (9 downto 0) := "0100110110";
    constant ap_const_lv10_26D : STD_LOGIC_VECTOR (9 downto 0) := "1001101101";
    constant ap_const_lv12_B02 : STD_LOGIC_VECTOR (11 downto 0) := "101100000010";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv12_A08 : STD_LOGIC_VECTOR (11 downto 0) := "101000001000";
    constant ap_const_lv12_989 : STD_LOGIC_VECTOR (11 downto 0) := "100110001001";
    constant ap_const_lv12_94A : STD_LOGIC_VECTOR (11 downto 0) := "100101001010";
    constant ap_const_lv12_92B : STD_LOGIC_VECTOR (11 downto 0) := "100100101011";
    constant ap_const_lv12_91C : STD_LOGIC_VECTOR (11 downto 0) := "100100011100";
    constant ap_const_lv12_915 : STD_LOGIC_VECTOR (11 downto 0) := "100100010101";
    constant ap_const_lv12_912 : STD_LOGIC_VECTOR (11 downto 0) := "100100010010";
    constant ap_const_lv12_911 : STD_LOGIC_VECTOR (11 downto 0) := "100100010001";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_Val2_4_2_fu_318_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_2_reg_1188 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_2_fu_324_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_2_reg_1195 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_16_reg_1202 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1208 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_1214 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_37_reg_1220 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_reg_1226 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_reg_1232 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_70_reg_1238 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_79_reg_1244 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_4_4_fu_596_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_4_reg_1250 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal p_Val2_7_4_fu_602_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_4_reg_1257 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_6_fu_778_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_6_reg_1264 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_Val2_7_6_fu_784_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_6_reg_1271 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_8_fu_976_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_8_reg_1278 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal p_Val2_7_8_fu_982_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_8_reg_1285 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_1_fu_130_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_fu_146_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_13_fu_160_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_152_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal mt7_1_fu_184_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal OP1_V_2_1_fu_176_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal r_V_1_1_fu_192_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Val2_4_1_fu_200_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_4_cast_cast_fu_168_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_7_fu_138_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_7_1_fu_210_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_Val2_10_1_fu_220_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_cast_fu_234_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_fu_244_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal mt_2_fu_238_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_14_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_258_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_2_fu_254_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_5_fu_268_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt7_2_fu_280_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_7_fu_286_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_296_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_10_fu_306_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_Val2_4_1_cast_fu_206_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_9_fu_314_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_6_fu_276_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_7_1_cast_fu_216_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_2_fu_330_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_3_fu_344_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_4_fu_358_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_5_fu_372_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_6_fu_386_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_7_fu_400_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_8_fu_414_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_10_9_fu_428_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mt_3_fu_442_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_19_fu_456_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_11_fu_447_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_16_v_fu_466_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal mt7_3_fu_477_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_20_fu_491_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_17_fu_482_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_22_v_fu_501_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_12_fu_508_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_473_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_3_fu_512_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mt_4_fu_522_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_25_fu_538_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_528_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_28_v_fu_548_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_7_3_fu_517_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal mt7_4_fu_559_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_28_fu_575_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_26_fu_565_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_v_fu_585_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_592_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_15_fu_555_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal mt_5_fu_608_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_32_fu_622_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_31_fu_613_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_40_v_fu_632_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mt7_5_fu_643_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_35_fu_657_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_34_fu_648_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_46_v_fu_667_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_24_fu_674_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_21_fu_639_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_5_fu_678_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_6_cast_fu_688_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_38_fu_698_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal mt_6_fu_692_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_41_fu_712_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_40_fu_708_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_43_fu_722_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_Val2_7_5_fu_683_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_2_6_cast_fu_733_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_44_fu_743_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal mt7_6_fu_737_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_47_fu_757_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_46_fu_753_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_49_fu_767_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_30_fu_774_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_27_fu_729_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_7_cast_fu_790_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_52_fu_799_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal mt_7_fu_793_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_55_fu_812_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_53_fu_808_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_56_fu_822_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal OP1_V_2_7_cast_fu_833_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_57_fu_842_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal mt7_7_fu_836_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_59_fu_855_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_58_fu_851_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_60_fu_865_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_36_fu_872_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_33_fu_829_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_7_fu_876_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_8_cast_fu_886_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_62_fu_896_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal mt_8_fu_890_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_64_fu_910_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_63_fu_906_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_65_fu_920_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_Val2_7_7_fu_881_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_2_8_cast_fu_931_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_66_fu_941_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal mt7_8_fu_935_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_68_fu_955_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_67_fu_951_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_69_fu_965_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_42_fu_972_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_39_fu_927_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_9_cast_fu_988_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_71_fu_997_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal mt_9_fu_991_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_73_fu_1010_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_72_fu_1006_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_74_fu_1020_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal OP1_V_2_9_cast_fu_1031_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_75_fu_1040_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal mt7_9_fu_1034_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_77_fu_1053_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_76_fu_1049_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_78_fu_1063_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_48_fu_1070_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_45_fu_1027_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_Val2_4_9_fu_1074_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_2_cast_fu_1084_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_80_fu_1094_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mt_s_fu_1088_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_82_fu_1108_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_81_fu_1104_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_83_fu_1118_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_Val2_7_9_fu_1079_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal OP1_V_2_cast_10_fu_1129_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_84_fu_1139_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal mt7_s_fu_1133_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_86_fu_1153_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_85_fu_1149_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_87_fu_1163_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_54_fu_1170_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_51_fu_1125_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                p_Val2_4_2_reg_1188 <= p_Val2_4_2_fu_318_p2;
                p_Val2_7_2_reg_1195 <= p_Val2_7_2_fu_324_p2;
                tmp_16_reg_1202 <= p_Val2_10_2_fu_330_p2(11 downto 11);
                tmp_22_reg_1208 <= p_Val2_10_3_fu_344_p2(11 downto 11);
                tmp_29_reg_1214 <= p_Val2_10_4_fu_358_p2(11 downto 11);
                tmp_37_reg_1220 <= p_Val2_10_5_fu_372_p2(11 downto 11);
                tmp_50_reg_1226 <= p_Val2_10_6_fu_386_p2(11 downto 11);
                tmp_61_reg_1232 <= p_Val2_10_7_fu_400_p2(11 downto 11);
                tmp_70_reg_1238 <= p_Val2_10_8_fu_414_p2(11 downto 11);
                tmp_79_reg_1244 <= p_Val2_10_9_fu_428_p2(11 downto 11);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                p_Val2_4_4_reg_1250 <= p_Val2_4_4_fu_596_p2;
                p_Val2_7_4_reg_1257 <= p_Val2_7_4_fu_602_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_Val2_4_6_reg_1264 <= p_Val2_4_6_fu_778_p2;
                p_Val2_7_6_reg_1271 <= p_Val2_7_6_fu_784_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                p_Val2_4_8_reg_1278 <= p_Val2_4_8_fu_976_p2;
                p_Val2_7_8_reg_1285 <= p_Val2_7_8_fu_982_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    OP1_V_2_1_fu_176_p3 <= 
        ap_const_lv10_2C9 when (tmp_1_fu_130_p3(0) = '1') else 
        ap_const_lv10_136;
        OP1_V_2_6_cast_fu_733_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_5_fu_683_p2),13));

        OP1_V_2_7_cast_fu_833_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_6_reg_1271),13));

        OP1_V_2_8_cast_fu_931_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_7_fu_881_p2),13));

        OP1_V_2_9_cast_fu_1031_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_8_reg_1285),13));

        OP1_V_2_cast_10_fu_1129_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_9_fu_1079_p2),13));

        OP1_V_2_cast_fu_1084_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_9_fu_1074_p2),13));

        OP1_V_6_cast_fu_688_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_5_fu_678_p2),13));

        OP1_V_7_cast_fu_790_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_6_reg_1264),13));

        OP1_V_8_cast_fu_886_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_7_fu_876_p2),13));

        OP1_V_9_cast_fu_988_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_4_8_reg_1278),13));

    OP1_V_cast_fu_234_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_4_1_fu_200_p2),11));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_done_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    c_V <= std_logic_vector(unsigned(p_Val2_4_9_fu_1074_p2) - unsigned(tmp_54_fu_1170_p1));

    c_V_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            c_V_ap_vld <= ap_const_logic_1;
        else 
            c_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    mt7_1_fu_184_p3 <= 
        ap_const_lv10_136 when (tmp_1_fu_130_p3(0) = '1') else 
        ap_const_lv10_2C9;
    mt7_2_fu_280_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(p_Val2_7_1_fu_210_p2));
    mt7_3_fu_477_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_7_2_reg_1195));
    mt7_4_fu_559_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_7_3_fu_517_p2));
    mt7_5_fu_643_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_7_4_reg_1257));
    mt7_6_fu_737_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_6_cast_fu_733_p1));
    mt7_7_fu_836_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_7_cast_fu_833_p1));
    mt7_8_fu_935_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_8_cast_fu_931_p1));
    mt7_9_fu_1034_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_9_cast_fu_1031_p1));
    mt7_s_fu_1133_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_cast_10_fu_1129_p1));
    mt_2_fu_238_p2 <= std_logic_vector(unsigned(ap_const_lv11_0) - unsigned(OP1_V_cast_fu_234_p1));
    mt_3_fu_442_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_4_2_reg_1188));
    mt_4_fu_522_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_4_3_fu_512_p2));
    mt_5_fu_608_p2 <= std_logic_vector(unsigned(ap_const_lv12_0) - unsigned(p_Val2_4_4_reg_1250));
    mt_6_fu_692_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_6_cast_fu_688_p1));
    mt_7_fu_793_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_7_cast_fu_790_p1));
    mt_8_fu_890_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_8_cast_fu_886_p1));
    mt_9_fu_991_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_9_cast_fu_988_p1));
    mt_s_fu_1088_p2 <= std_logic_vector(unsigned(ap_const_lv13_0) - unsigned(OP1_V_2_cast_fu_1084_p1));
    p_Val2_10_1_fu_220_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_B02));
    p_Val2_10_2_fu_330_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_A08));
    p_Val2_10_3_fu_344_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_989));
    p_Val2_10_4_fu_358_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_94A));
    p_Val2_10_5_fu_372_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_92B));
    p_Val2_10_6_fu_386_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_91C));
    p_Val2_10_7_fu_400_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_915));
    p_Val2_10_8_fu_414_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_912));
    p_Val2_10_9_fu_428_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_911));
    p_Val2_4_1_cast_fu_206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_Val2_4_1_fu_200_p2),12));
    p_Val2_4_1_fu_200_p2 <= std_logic_vector(signed(ap_const_lv10_26D) - signed(r_V_1_1_fu_192_p3));
    p_Val2_4_2_fu_318_p2 <= std_logic_vector(unsigned(p_Val2_4_1_cast_fu_206_p1) - unsigned(tmp_9_fu_314_p1));
    p_Val2_4_3_fu_512_p2 <= std_logic_vector(unsigned(p_Val2_4_2_reg_1188) - unsigned(tmp_12_fu_508_p1));
    p_Val2_4_4_fu_596_p2 <= std_logic_vector(unsigned(p_Val2_4_3_fu_512_p2) - unsigned(tmp_18_fu_592_p1));
    p_Val2_4_5_fu_678_p2 <= std_logic_vector(unsigned(p_Val2_4_4_reg_1250) - unsigned(tmp_24_fu_674_p1));
    p_Val2_4_6_fu_778_p2 <= std_logic_vector(unsigned(p_Val2_4_5_fu_678_p2) - unsigned(tmp_30_fu_774_p1));
    p_Val2_4_7_fu_876_p2 <= std_logic_vector(unsigned(p_Val2_4_6_reg_1264) - unsigned(tmp_36_fu_872_p1));
    p_Val2_4_8_fu_976_p2 <= std_logic_vector(unsigned(p_Val2_4_7_fu_876_p2) - unsigned(tmp_42_fu_972_p1));
    p_Val2_4_9_fu_1074_p2 <= std_logic_vector(unsigned(p_Val2_4_8_reg_1278) - unsigned(tmp_48_fu_1070_p1));
        p_Val2_7_1_cast_fu_216_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Val2_7_1_fu_210_p2),12));

    p_Val2_7_1_fu_210_p2 <= std_logic_vector(unsigned(tmp_4_cast_cast_fu_168_p3) + unsigned(p_Val2_7_fu_138_p3));
    p_Val2_7_2_fu_324_p2 <= std_logic_vector(signed(tmp_6_fu_276_p1) + signed(p_Val2_7_1_cast_fu_216_p1));
    p_Val2_7_3_fu_517_p2 <= std_logic_vector(signed(tmp_s_fu_473_p1) + signed(p_Val2_7_2_reg_1195));
    p_Val2_7_4_fu_602_p2 <= std_logic_vector(signed(tmp_15_fu_555_p1) + signed(p_Val2_7_3_fu_517_p2));
    p_Val2_7_5_fu_683_p2 <= std_logic_vector(signed(tmp_21_fu_639_p1) + signed(p_Val2_7_4_reg_1257));
    p_Val2_7_6_fu_784_p2 <= std_logic_vector(signed(tmp_27_fu_729_p1) + signed(p_Val2_7_5_fu_683_p2));
    p_Val2_7_7_fu_881_p2 <= std_logic_vector(signed(tmp_33_fu_829_p1) + signed(p_Val2_7_6_reg_1271));
    p_Val2_7_8_fu_982_p2 <= std_logic_vector(signed(tmp_39_fu_927_p1) + signed(p_Val2_7_7_fu_881_p2));
    p_Val2_7_9_fu_1079_p2 <= std_logic_vector(signed(tmp_45_fu_1027_p1) + signed(p_Val2_7_8_reg_1285));
    p_Val2_7_fu_138_p3 <= 
        ap_const_lv11_593 when (tmp_1_fu_130_p3(0) = '1') else 
        ap_const_lv11_26D;
    p_Val2_s_fu_146_p2 <= std_logic_vector(unsigned(theta_V) + unsigned(ap_const_lv12_CDC));
    r_V_1_1_fu_192_p3 <= 
        mt7_1_fu_184_p3 when (tmp_3_fu_152_p3(0) = '1') else 
        OP1_V_2_1_fu_176_p3;
    s_V <= std_logic_vector(signed(tmp_51_fu_1125_p1) + signed(p_Val2_7_9_fu_1079_p2));

    s_V_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            s_V_ap_vld <= ap_const_logic_1;
        else 
            s_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_306_p3 <= 
        tmp_7_fu_286_p4 when (tmp_14_fu_226_p3(0) = '1') else 
        tmp_8_fu_296_p4;
    tmp_11_fu_447_p4 <= p_Val2_4_2_reg_1188(11 downto 3);
        tmp_12_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_22_v_fu_501_p3),12));

    tmp_13_fu_160_p3 <= p_Val2_s_fu_146_p2(11 downto 11);
    tmp_14_fu_226_p3 <= p_Val2_10_1_fu_220_p2(11 downto 11);
        tmp_15_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_28_v_fu_548_p3),12));

    tmp_16_v_fu_466_p3 <= 
        tmp_19_fu_456_p4 when (tmp_16_reg_1202(0) = '1') else 
        tmp_11_fu_447_p4;
    tmp_17_fu_482_p4 <= p_Val2_7_2_reg_1195(11 downto 3);
        tmp_18_fu_592_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_34_v_fu_585_p3),12));

    tmp_19_fu_456_p4 <= mt_3_fu_442_p2(11 downto 3);
    tmp_1_fu_130_p3 <= theta_V(11 downto 11);
    tmp_20_fu_491_p4 <= mt7_3_fu_477_p2(11 downto 3);
        tmp_21_fu_639_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_40_v_fu_632_p3),12));

    tmp_22_v_fu_501_p3 <= 
        tmp_20_fu_491_p4 when (tmp_16_reg_1202(0) = '1') else 
        tmp_17_fu_482_p4;
    tmp_23_fu_528_p4 <= p_Val2_4_3_fu_512_p2(11 downto 4);
        tmp_24_fu_674_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_46_v_fu_667_p3),12));

    tmp_25_fu_538_p4 <= mt_4_fu_522_p2(11 downto 4);
    tmp_26_fu_565_p4 <= p_Val2_7_3_fu_517_p2(11 downto 4);
        tmp_27_fu_729_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_43_fu_722_p3),12));

    tmp_28_fu_575_p4 <= mt7_4_fu_559_p2(11 downto 4);
    tmp_28_v_fu_548_p3 <= 
        tmp_25_fu_538_p4 when (tmp_22_reg_1208(0) = '1') else 
        tmp_23_fu_528_p4;
    tmp_2_fu_254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_244_p4),9));
        tmp_30_fu_774_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_49_fu_767_p3),12));

    tmp_31_fu_613_p4 <= p_Val2_4_4_reg_1250(11 downto 5);
    tmp_32_fu_622_p4 <= mt_5_fu_608_p2(11 downto 5);
        tmp_33_fu_829_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_56_fu_822_p3),12));

    tmp_34_fu_648_p4 <= p_Val2_7_4_reg_1257(11 downto 5);
    tmp_34_v_fu_585_p3 <= 
        tmp_28_fu_575_p4 when (tmp_22_reg_1208(0) = '1') else 
        tmp_26_fu_565_p4;
    tmp_35_fu_657_p4 <= mt7_5_fu_643_p2(11 downto 5);
        tmp_36_fu_872_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_60_fu_865_p3),12));

    tmp_38_fu_698_p4 <= p_Val2_4_5_fu_678_p2(11 downto 6);
        tmp_39_fu_927_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_65_fu_920_p3),12));

    tmp_3_fu_152_p3 <= p_Val2_s_fu_146_p2(11 downto 11);
        tmp_40_fu_708_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_38_fu_698_p4),7));

    tmp_40_v_fu_632_p3 <= 
        tmp_32_fu_622_p4 when (tmp_29_reg_1214(0) = '1') else 
        tmp_31_fu_613_p4;
    tmp_41_fu_712_p4 <= mt_6_fu_692_p2(12 downto 6);
        tmp_42_fu_972_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_69_fu_965_p3),12));

    tmp_43_fu_722_p3 <= 
        tmp_41_fu_712_p4 when (tmp_37_reg_1220(0) = '1') else 
        tmp_40_fu_708_p1;
    tmp_44_fu_743_p4 <= p_Val2_7_5_fu_683_p2(11 downto 6);
        tmp_45_fu_1027_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_74_fu_1020_p3),12));

        tmp_46_fu_753_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_44_fu_743_p4),7));

    tmp_46_v_fu_667_p3 <= 
        tmp_35_fu_657_p4 when (tmp_29_reg_1214(0) = '1') else 
        tmp_34_fu_648_p4;
    tmp_47_fu_757_p4 <= mt7_6_fu_737_p2(12 downto 6);
        tmp_48_fu_1070_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_78_fu_1063_p3),12));

    tmp_49_fu_767_p3 <= 
        tmp_47_fu_757_p4 when (tmp_37_reg_1220(0) = '1') else 
        tmp_46_fu_753_p1;
    tmp_4_cast_cast_fu_168_p3 <= 
        ap_const_lv11_6C9 when (tmp_13_fu_160_p3(0) = '1') else 
        ap_const_lv11_136;
    tmp_4_fu_258_p4 <= mt_2_fu_238_p2(10 downto 2);
        tmp_51_fu_1125_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_83_fu_1118_p3),12));

    tmp_52_fu_799_p4 <= p_Val2_4_6_reg_1264(11 downto 7);
        tmp_53_fu_808_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_52_fu_799_p4),6));

        tmp_54_fu_1170_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_87_fu_1163_p3),12));

    tmp_55_fu_812_p4 <= mt_7_fu_793_p2(12 downto 7);
    tmp_56_fu_822_p3 <= 
        tmp_55_fu_812_p4 when (tmp_50_reg_1226(0) = '1') else 
        tmp_53_fu_808_p1;
    tmp_57_fu_842_p4 <= p_Val2_7_6_reg_1271(11 downto 7);
        tmp_58_fu_851_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_57_fu_842_p4),6));

    tmp_59_fu_855_p4 <= mt7_7_fu_836_p2(12 downto 7);
    tmp_5_fu_268_p3 <= 
        tmp_4_fu_258_p4 when (tmp_14_fu_226_p3(0) = '1') else 
        tmp_2_fu_254_p1;
    tmp_60_fu_865_p3 <= 
        tmp_59_fu_855_p4 when (tmp_50_reg_1226(0) = '1') else 
        tmp_58_fu_851_p1;
    tmp_62_fu_896_p4 <= p_Val2_4_7_fu_876_p2(11 downto 8);
        tmp_63_fu_906_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_62_fu_896_p4),5));

    tmp_64_fu_910_p4 <= mt_8_fu_890_p2(12 downto 8);
    tmp_65_fu_920_p3 <= 
        tmp_64_fu_910_p4 when (tmp_61_reg_1232(0) = '1') else 
        tmp_63_fu_906_p1;
    tmp_66_fu_941_p4 <= p_Val2_7_7_fu_881_p2(11 downto 8);
        tmp_67_fu_951_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_66_fu_941_p4),5));

    tmp_68_fu_955_p4 <= mt7_8_fu_935_p2(12 downto 8);
    tmp_69_fu_965_p3 <= 
        tmp_68_fu_955_p4 when (tmp_61_reg_1232(0) = '1') else 
        tmp_67_fu_951_p1;
        tmp_6_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_5_fu_268_p3),12));

    tmp_71_fu_997_p4 <= p_Val2_4_8_reg_1278(11 downto 9);
        tmp_72_fu_1006_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_71_fu_997_p4),4));

    tmp_73_fu_1010_p4 <= mt_9_fu_991_p2(12 downto 9);
    tmp_74_fu_1020_p3 <= 
        tmp_73_fu_1010_p4 when (tmp_70_reg_1238(0) = '1') else 
        tmp_72_fu_1006_p1;
    tmp_75_fu_1040_p4 <= p_Val2_7_8_reg_1285(11 downto 9);
        tmp_76_fu_1049_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_75_fu_1040_p4),4));

    tmp_77_fu_1053_p4 <= mt7_9_fu_1034_p2(12 downto 9);
    tmp_78_fu_1063_p3 <= 
        tmp_77_fu_1053_p4 when (tmp_70_reg_1238(0) = '1') else 
        tmp_76_fu_1049_p1;
    tmp_7_fu_286_p4 <= mt7_2_fu_280_p2(10 downto 2);
    tmp_80_fu_1094_p4 <= p_Val2_4_9_fu_1074_p2(11 downto 10);
        tmp_81_fu_1104_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_80_fu_1094_p4),3));

    tmp_82_fu_1108_p4 <= mt_s_fu_1088_p2(12 downto 10);
    tmp_83_fu_1118_p3 <= 
        tmp_82_fu_1108_p4 when (tmp_79_reg_1244(0) = '1') else 
        tmp_81_fu_1104_p1;
    tmp_84_fu_1139_p4 <= p_Val2_7_9_fu_1079_p2(11 downto 10);
        tmp_85_fu_1149_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_84_fu_1139_p4),3));

    tmp_86_fu_1153_p4 <= mt7_s_fu_1133_p2(12 downto 10);
    tmp_87_fu_1163_p3 <= 
        tmp_86_fu_1153_p4 when (tmp_79_reg_1244(0) = '1') else 
        tmp_85_fu_1149_p1;
    tmp_8_fu_296_p4 <= p_Val2_7_1_fu_210_p2(10 downto 2);
        tmp_9_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_10_fu_306_p3),12));

    tmp_fu_244_p4 <= p_Val2_4_1_fu_200_p2(9 downto 2);
        tmp_s_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_16_v_fu_466_p3),12));

end behav;
