// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.op
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pipe3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pipe3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pipe3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> pipe3::ap_ST_fsm_state1 = "1";
const sc_lv<3> pipe3::ap_ST_fsm_state2 = "10";
const sc_lv<3> pipe3::ap_ST_fsm_state3 = "100";
const sc_lv<32> pipe3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pipe3::ap_const_lv32_1 = "1";
const sc_lv<32> pipe3::ap_const_lv32_2 = "10";
const bool pipe3::ap_const_boolean_1 = true;

pipe3::pipe3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    pipe3_mul_32s_32sbkb_U1 = new pipe3_mul_32s_32sbkb<1,2,32,32,32>("pipe3_mul_32s_32sbkb_U1");
    pipe3_mul_32s_32sbkb_U1->clk(ap_clk);
    pipe3_mul_32s_32sbkb_U1->reset(ap_rst);
    pipe3_mul_32s_32sbkb_U1->din0(b);
    pipe3_mul_32s_32sbkb_U1->din1(a);
    pipe3_mul_32s_32sbkb_U1->ce(ap_var_for_const0);
    pipe3_mul_32s_32sbkb_U1->dout(grp_fu_35_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_out_r);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp1_fu_41_p2 );
    sensitive << ( tmp_2_fu_45_p1 );

    SC_METHOD(thread_out_r_ap_vld);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp1_fu_41_p1);
    sensitive << ( a );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp1_fu_41_p2);
    sensitive << ( tmp_reg_63 );
    sensitive << ( tmp1_fu_41_p1 );

    SC_METHOD(thread_tmp_2_fu_45_p1);
    sensitive << ( b );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pipe3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, b, "(port)b");
    sc_trace(mVcdFile, out_r, "(port)out_r");
    sc_trace(mVcdFile, out_r_ap_vld, "(port)out_r_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_35_p2, "grp_fu_35_p2");
    sc_trace(mVcdFile, tmp_reg_63, "tmp_reg_63");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp1_fu_41_p1, "tmp1_fu_41_p1");
    sc_trace(mVcdFile, tmp1_fu_41_p2, "tmp1_fu_41_p2");
    sc_trace(mVcdFile, tmp_2_fu_45_p1, "tmp_2_fu_45_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("pipe3.hdltvin.dat");
    mHdltvoutHandle.open("pipe3.hdltvout.dat");
}

pipe3::~pipe3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete pipe3_mul_32s_32sbkb_U1;
}

void pipe3::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void pipe3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        tmp_reg_63 = grp_fu_35_p2.read();
    }
}

void pipe3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pipe3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pipe3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pipe3::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pipe3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pipe3::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pipe3::thread_out_r() {
    out_r = (!tmp1_fu_41_p2.read().is_01() || !tmp_2_fu_45_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp1_fu_41_p2.read()) + sc_bigint<32>(tmp_2_fu_45_p1.read()));
}

void pipe3::thread_out_r_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        out_r_ap_vld = ap_const_logic_1;
    } else {
        out_r_ap_vld = ap_const_logic_0;
    }
}

void pipe3::thread_tmp1_fu_41_p1() {
    tmp1_fu_41_p1 = a.read();
}

void pipe3::thread_tmp1_fu_41_p2() {
    tmp1_fu_41_p2 = (!tmp_reg_63.read().is_01() || !tmp1_fu_41_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_reg_63.read()) + sc_bigint<32>(tmp1_fu_41_p1.read()));
}

void pipe3::thread_tmp_2_fu_45_p1() {
    tmp_2_fu_45_p1 = b.read();
}

void pipe3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void pipe3::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a\" :  \"" << a.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b\" :  \"" << b.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r\" :  \"" << out_r.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_ap_vld\" :  \"" << out_r_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

