// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordic.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordic::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordic::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> cordic::ap_ST_fsm_state1 = "1";
const sc_lv<5> cordic::ap_ST_fsm_state2 = "10";
const sc_lv<5> cordic::ap_ST_fsm_state3 = "100";
const sc_lv<5> cordic::ap_ST_fsm_state4 = "1000";
const sc_lv<5> cordic::ap_ST_fsm_state5 = "10000";
const sc_lv<32> cordic::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cordic::ap_const_lv32_1 = "1";
const sc_lv<32> cordic::ap_const_lv32_2 = "10";
const sc_lv<32> cordic::ap_const_lv32_3 = "11";
const sc_lv<32> cordic::ap_const_lv32_4 = "100";
const sc_lv<32> cordic::ap_const_lv32_B = "1011";
const sc_lv<11> cordic::ap_const_lv11_593 = "10110010011";
const sc_lv<11> cordic::ap_const_lv11_26D = "1001101101";
const sc_lv<12> cordic::ap_const_lv12_CDC = "110011011100";
const sc_lv<11> cordic::ap_const_lv11_6C9 = "11011001001";
const sc_lv<11> cordic::ap_const_lv11_136 = "100110110";
const sc_lv<10> cordic::ap_const_lv10_2C9 = "1011001001";
const sc_lv<10> cordic::ap_const_lv10_136 = "100110110";
const sc_lv<10> cordic::ap_const_lv10_26D = "1001101101";
const sc_lv<12> cordic::ap_const_lv12_B02 = "101100000010";
const sc_lv<11> cordic::ap_const_lv11_0 = "00000000000";
const sc_lv<32> cordic::ap_const_lv32_9 = "1001";
const sc_lv<32> cordic::ap_const_lv32_A = "1010";
const sc_lv<12> cordic::ap_const_lv12_A08 = "101000001000";
const sc_lv<12> cordic::ap_const_lv12_989 = "100110001001";
const sc_lv<12> cordic::ap_const_lv12_94A = "100101001010";
const sc_lv<12> cordic::ap_const_lv12_92B = "100100101011";
const sc_lv<12> cordic::ap_const_lv12_91C = "100100011100";
const sc_lv<12> cordic::ap_const_lv12_915 = "100100010101";
const sc_lv<12> cordic::ap_const_lv12_912 = "100100010010";
const sc_lv<12> cordic::ap_const_lv12_911 = "100100010001";
const sc_lv<12> cordic::ap_const_lv12_0 = "000000000000";
const sc_lv<32> cordic::ap_const_lv32_5 = "101";
const sc_lv<13> cordic::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> cordic::ap_const_lv32_6 = "110";
const sc_lv<32> cordic::ap_const_lv32_C = "1100";
const sc_lv<32> cordic::ap_const_lv32_7 = "111";
const sc_lv<32> cordic::ap_const_lv32_8 = "1000";
const bool cordic::ap_const_boolean_1 = true;

cordic::cordic(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_2_1_fu_176_p3);
    sensitive << ( tmp_1_fu_130_p3 );

    SC_METHOD(thread_OP1_V_2_6_cast_fu_733_p1);
    sensitive << ( p_Val2_7_5_fu_683_p2 );

    SC_METHOD(thread_OP1_V_2_7_cast_fu_833_p1);
    sensitive << ( p_Val2_7_6_reg_1271 );

    SC_METHOD(thread_OP1_V_2_8_cast_fu_931_p1);
    sensitive << ( p_Val2_7_7_fu_881_p2 );

    SC_METHOD(thread_OP1_V_2_9_cast_fu_1031_p1);
    sensitive << ( p_Val2_7_8_reg_1285 );

    SC_METHOD(thread_OP1_V_2_cast_10_fu_1129_p1);
    sensitive << ( p_Val2_7_9_fu_1079_p2 );

    SC_METHOD(thread_OP1_V_2_cast_fu_1084_p1);
    sensitive << ( p_Val2_4_9_fu_1074_p2 );

    SC_METHOD(thread_OP1_V_6_cast_fu_688_p1);
    sensitive << ( p_Val2_4_5_fu_678_p2 );

    SC_METHOD(thread_OP1_V_7_cast_fu_790_p1);
    sensitive << ( p_Val2_4_6_reg_1264 );

    SC_METHOD(thread_OP1_V_8_cast_fu_886_p1);
    sensitive << ( p_Val2_4_7_fu_876_p2 );

    SC_METHOD(thread_OP1_V_9_cast_fu_988_p1);
    sensitive << ( p_Val2_4_8_reg_1278 );

    SC_METHOD(thread_OP1_V_cast_fu_234_p1);
    sensitive << ( p_Val2_4_1_fu_200_p2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_c_V);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_Val2_4_9_fu_1074_p2 );
    sensitive << ( tmp_54_fu_1170_p1 );

    SC_METHOD(thread_c_V_ap_vld);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_mt7_1_fu_184_p3);
    sensitive << ( tmp_1_fu_130_p3 );

    SC_METHOD(thread_mt7_2_fu_280_p2);
    sensitive << ( p_Val2_7_1_fu_210_p2 );

    SC_METHOD(thread_mt7_3_fu_477_p2);
    sensitive << ( p_Val2_7_2_reg_1195 );

    SC_METHOD(thread_mt7_4_fu_559_p2);
    sensitive << ( p_Val2_7_3_fu_517_p2 );

    SC_METHOD(thread_mt7_5_fu_643_p2);
    sensitive << ( p_Val2_7_4_reg_1257 );

    SC_METHOD(thread_mt7_6_fu_737_p2);
    sensitive << ( OP1_V_2_6_cast_fu_733_p1 );

    SC_METHOD(thread_mt7_7_fu_836_p2);
    sensitive << ( OP1_V_2_7_cast_fu_833_p1 );

    SC_METHOD(thread_mt7_8_fu_935_p2);
    sensitive << ( OP1_V_2_8_cast_fu_931_p1 );

    SC_METHOD(thread_mt7_9_fu_1034_p2);
    sensitive << ( OP1_V_2_9_cast_fu_1031_p1 );

    SC_METHOD(thread_mt7_s_fu_1133_p2);
    sensitive << ( OP1_V_2_cast_10_fu_1129_p1 );

    SC_METHOD(thread_mt_2_fu_238_p2);
    sensitive << ( OP1_V_cast_fu_234_p1 );

    SC_METHOD(thread_mt_3_fu_442_p2);
    sensitive << ( p_Val2_4_2_reg_1188 );

    SC_METHOD(thread_mt_4_fu_522_p2);
    sensitive << ( p_Val2_4_3_fu_512_p2 );

    SC_METHOD(thread_mt_5_fu_608_p2);
    sensitive << ( p_Val2_4_4_reg_1250 );

    SC_METHOD(thread_mt_6_fu_692_p2);
    sensitive << ( OP1_V_6_cast_fu_688_p1 );

    SC_METHOD(thread_mt_7_fu_793_p2);
    sensitive << ( OP1_V_7_cast_fu_790_p1 );

    SC_METHOD(thread_mt_8_fu_890_p2);
    sensitive << ( OP1_V_8_cast_fu_886_p1 );

    SC_METHOD(thread_mt_9_fu_991_p2);
    sensitive << ( OP1_V_9_cast_fu_988_p1 );

    SC_METHOD(thread_mt_s_fu_1088_p2);
    sensitive << ( OP1_V_2_cast_fu_1084_p1 );

    SC_METHOD(thread_p_Val2_10_1_fu_220_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_2_fu_330_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_3_fu_344_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_4_fu_358_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_5_fu_372_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_6_fu_386_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_7_fu_400_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_8_fu_414_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_10_9_fu_428_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_p_Val2_4_1_cast_fu_206_p1);
    sensitive << ( p_Val2_4_1_fu_200_p2 );

    SC_METHOD(thread_p_Val2_4_1_fu_200_p2);
    sensitive << ( r_V_1_1_fu_192_p3 );

    SC_METHOD(thread_p_Val2_4_2_fu_318_p2);
    sensitive << ( p_Val2_4_1_cast_fu_206_p1 );
    sensitive << ( tmp_9_fu_314_p1 );

    SC_METHOD(thread_p_Val2_4_3_fu_512_p2);
    sensitive << ( p_Val2_4_2_reg_1188 );
    sensitive << ( tmp_12_fu_508_p1 );

    SC_METHOD(thread_p_Val2_4_4_fu_596_p2);
    sensitive << ( p_Val2_4_3_fu_512_p2 );
    sensitive << ( tmp_18_fu_592_p1 );

    SC_METHOD(thread_p_Val2_4_5_fu_678_p2);
    sensitive << ( p_Val2_4_4_reg_1250 );
    sensitive << ( tmp_24_fu_674_p1 );

    SC_METHOD(thread_p_Val2_4_6_fu_778_p2);
    sensitive << ( p_Val2_4_5_fu_678_p2 );
    sensitive << ( tmp_30_fu_774_p1 );

    SC_METHOD(thread_p_Val2_4_7_fu_876_p2);
    sensitive << ( p_Val2_4_6_reg_1264 );
    sensitive << ( tmp_36_fu_872_p1 );

    SC_METHOD(thread_p_Val2_4_8_fu_976_p2);
    sensitive << ( p_Val2_4_7_fu_876_p2 );
    sensitive << ( tmp_42_fu_972_p1 );

    SC_METHOD(thread_p_Val2_4_9_fu_1074_p2);
    sensitive << ( p_Val2_4_8_reg_1278 );
    sensitive << ( tmp_48_fu_1070_p1 );

    SC_METHOD(thread_p_Val2_7_1_cast_fu_216_p1);
    sensitive << ( p_Val2_7_1_fu_210_p2 );

    SC_METHOD(thread_p_Val2_7_1_fu_210_p2);
    sensitive << ( tmp_4_cast_cast_fu_168_p3 );
    sensitive << ( p_Val2_7_fu_138_p3 );

    SC_METHOD(thread_p_Val2_7_2_fu_324_p2);
    sensitive << ( tmp_6_fu_276_p1 );
    sensitive << ( p_Val2_7_1_cast_fu_216_p1 );

    SC_METHOD(thread_p_Val2_7_3_fu_517_p2);
    sensitive << ( p_Val2_7_2_reg_1195 );
    sensitive << ( tmp_s_fu_473_p1 );

    SC_METHOD(thread_p_Val2_7_4_fu_602_p2);
    sensitive << ( p_Val2_7_3_fu_517_p2 );
    sensitive << ( tmp_15_fu_555_p1 );

    SC_METHOD(thread_p_Val2_7_5_fu_683_p2);
    sensitive << ( p_Val2_7_4_reg_1257 );
    sensitive << ( tmp_21_fu_639_p1 );

    SC_METHOD(thread_p_Val2_7_6_fu_784_p2);
    sensitive << ( p_Val2_7_5_fu_683_p2 );
    sensitive << ( tmp_27_fu_729_p1 );

    SC_METHOD(thread_p_Val2_7_7_fu_881_p2);
    sensitive << ( p_Val2_7_6_reg_1271 );
    sensitive << ( tmp_33_fu_829_p1 );

    SC_METHOD(thread_p_Val2_7_8_fu_982_p2);
    sensitive << ( p_Val2_7_7_fu_881_p2 );
    sensitive << ( tmp_39_fu_927_p1 );

    SC_METHOD(thread_p_Val2_7_9_fu_1079_p2);
    sensitive << ( p_Val2_7_8_reg_1285 );
    sensitive << ( tmp_45_fu_1027_p1 );

    SC_METHOD(thread_p_Val2_7_fu_138_p3);
    sensitive << ( tmp_1_fu_130_p3 );

    SC_METHOD(thread_p_Val2_s_fu_146_p2);
    sensitive << ( theta_V );

    SC_METHOD(thread_r_V_1_1_fu_192_p3);
    sensitive << ( tmp_3_fu_152_p3 );
    sensitive << ( mt7_1_fu_184_p3 );
    sensitive << ( OP1_V_2_1_fu_176_p3 );

    SC_METHOD(thread_s_V);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( p_Val2_7_9_fu_1079_p2 );
    sensitive << ( tmp_51_fu_1125_p1 );

    SC_METHOD(thread_s_V_ap_vld);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_tmp_10_fu_306_p3);
    sensitive << ( tmp_14_fu_226_p3 );
    sensitive << ( tmp_7_fu_286_p4 );
    sensitive << ( tmp_8_fu_296_p4 );

    SC_METHOD(thread_tmp_11_fu_447_p4);
    sensitive << ( p_Val2_4_2_reg_1188 );

    SC_METHOD(thread_tmp_12_fu_508_p1);
    sensitive << ( tmp_22_v_fu_501_p3 );

    SC_METHOD(thread_tmp_13_fu_160_p3);
    sensitive << ( p_Val2_s_fu_146_p2 );

    SC_METHOD(thread_tmp_14_fu_226_p3);
    sensitive << ( p_Val2_10_1_fu_220_p2 );

    SC_METHOD(thread_tmp_15_fu_555_p1);
    sensitive << ( tmp_28_v_fu_548_p3 );

    SC_METHOD(thread_tmp_16_v_fu_466_p3);
    sensitive << ( tmp_16_reg_1202 );
    sensitive << ( tmp_19_fu_456_p4 );
    sensitive << ( tmp_11_fu_447_p4 );

    SC_METHOD(thread_tmp_17_fu_482_p4);
    sensitive << ( p_Val2_7_2_reg_1195 );

    SC_METHOD(thread_tmp_18_fu_592_p1);
    sensitive << ( tmp_34_v_fu_585_p3 );

    SC_METHOD(thread_tmp_19_fu_456_p4);
    sensitive << ( mt_3_fu_442_p2 );

    SC_METHOD(thread_tmp_1_fu_130_p3);
    sensitive << ( theta_V );

    SC_METHOD(thread_tmp_20_fu_491_p4);
    sensitive << ( mt7_3_fu_477_p2 );

    SC_METHOD(thread_tmp_21_fu_639_p1);
    sensitive << ( tmp_40_v_fu_632_p3 );

    SC_METHOD(thread_tmp_22_v_fu_501_p3);
    sensitive << ( tmp_16_reg_1202 );
    sensitive << ( tmp_20_fu_491_p4 );
    sensitive << ( tmp_17_fu_482_p4 );

    SC_METHOD(thread_tmp_23_fu_528_p4);
    sensitive << ( p_Val2_4_3_fu_512_p2 );

    SC_METHOD(thread_tmp_24_fu_674_p1);
    sensitive << ( tmp_46_v_fu_667_p3 );

    SC_METHOD(thread_tmp_25_fu_538_p4);
    sensitive << ( mt_4_fu_522_p2 );

    SC_METHOD(thread_tmp_26_fu_565_p4);
    sensitive << ( p_Val2_7_3_fu_517_p2 );

    SC_METHOD(thread_tmp_27_fu_729_p1);
    sensitive << ( tmp_43_fu_722_p3 );

    SC_METHOD(thread_tmp_28_fu_575_p4);
    sensitive << ( mt7_4_fu_559_p2 );

    SC_METHOD(thread_tmp_28_v_fu_548_p3);
    sensitive << ( tmp_22_reg_1208 );
    sensitive << ( tmp_25_fu_538_p4 );
    sensitive << ( tmp_23_fu_528_p4 );

    SC_METHOD(thread_tmp_2_fu_254_p1);
    sensitive << ( tmp_fu_244_p4 );

    SC_METHOD(thread_tmp_30_fu_774_p1);
    sensitive << ( tmp_49_fu_767_p3 );

    SC_METHOD(thread_tmp_31_fu_613_p4);
    sensitive << ( p_Val2_4_4_reg_1250 );

    SC_METHOD(thread_tmp_32_fu_622_p4);
    sensitive << ( mt_5_fu_608_p2 );

    SC_METHOD(thread_tmp_33_fu_829_p1);
    sensitive << ( tmp_56_fu_822_p3 );

    SC_METHOD(thread_tmp_34_fu_648_p4);
    sensitive << ( p_Val2_7_4_reg_1257 );

    SC_METHOD(thread_tmp_34_v_fu_585_p3);
    sensitive << ( tmp_22_reg_1208 );
    sensitive << ( tmp_28_fu_575_p4 );
    sensitive << ( tmp_26_fu_565_p4 );

    SC_METHOD(thread_tmp_35_fu_657_p4);
    sensitive << ( mt7_5_fu_643_p2 );

    SC_METHOD(thread_tmp_36_fu_872_p1);
    sensitive << ( tmp_60_fu_865_p3 );

    SC_METHOD(thread_tmp_38_fu_698_p4);
    sensitive << ( p_Val2_4_5_fu_678_p2 );

    SC_METHOD(thread_tmp_39_fu_927_p1);
    sensitive << ( tmp_65_fu_920_p3 );

    SC_METHOD(thread_tmp_3_fu_152_p3);
    sensitive << ( p_Val2_s_fu_146_p2 );

    SC_METHOD(thread_tmp_40_fu_708_p1);
    sensitive << ( tmp_38_fu_698_p4 );

    SC_METHOD(thread_tmp_40_v_fu_632_p3);
    sensitive << ( tmp_29_reg_1214 );
    sensitive << ( tmp_32_fu_622_p4 );
    sensitive << ( tmp_31_fu_613_p4 );

    SC_METHOD(thread_tmp_41_fu_712_p4);
    sensitive << ( mt_6_fu_692_p2 );

    SC_METHOD(thread_tmp_42_fu_972_p1);
    sensitive << ( tmp_69_fu_965_p3 );

    SC_METHOD(thread_tmp_43_fu_722_p3);
    sensitive << ( tmp_37_reg_1220 );
    sensitive << ( tmp_41_fu_712_p4 );
    sensitive << ( tmp_40_fu_708_p1 );

    SC_METHOD(thread_tmp_44_fu_743_p4);
    sensitive << ( p_Val2_7_5_fu_683_p2 );

    SC_METHOD(thread_tmp_45_fu_1027_p1);
    sensitive << ( tmp_74_fu_1020_p3 );

    SC_METHOD(thread_tmp_46_fu_753_p1);
    sensitive << ( tmp_44_fu_743_p4 );

    SC_METHOD(thread_tmp_46_v_fu_667_p3);
    sensitive << ( tmp_29_reg_1214 );
    sensitive << ( tmp_35_fu_657_p4 );
    sensitive << ( tmp_34_fu_648_p4 );

    SC_METHOD(thread_tmp_47_fu_757_p4);
    sensitive << ( mt7_6_fu_737_p2 );

    SC_METHOD(thread_tmp_48_fu_1070_p1);
    sensitive << ( tmp_78_fu_1063_p3 );

    SC_METHOD(thread_tmp_49_fu_767_p3);
    sensitive << ( tmp_37_reg_1220 );
    sensitive << ( tmp_47_fu_757_p4 );
    sensitive << ( tmp_46_fu_753_p1 );

    SC_METHOD(thread_tmp_4_cast_cast_fu_168_p3);
    sensitive << ( tmp_13_fu_160_p3 );

    SC_METHOD(thread_tmp_4_fu_258_p4);
    sensitive << ( mt_2_fu_238_p2 );

    SC_METHOD(thread_tmp_51_fu_1125_p1);
    sensitive << ( tmp_83_fu_1118_p3 );

    SC_METHOD(thread_tmp_52_fu_799_p4);
    sensitive << ( p_Val2_4_6_reg_1264 );

    SC_METHOD(thread_tmp_53_fu_808_p1);
    sensitive << ( tmp_52_fu_799_p4 );

    SC_METHOD(thread_tmp_54_fu_1170_p1);
    sensitive << ( tmp_87_fu_1163_p3 );

    SC_METHOD(thread_tmp_55_fu_812_p4);
    sensitive << ( mt_7_fu_793_p2 );

    SC_METHOD(thread_tmp_56_fu_822_p3);
    sensitive << ( tmp_50_reg_1226 );
    sensitive << ( tmp_55_fu_812_p4 );
    sensitive << ( tmp_53_fu_808_p1 );

    SC_METHOD(thread_tmp_57_fu_842_p4);
    sensitive << ( p_Val2_7_6_reg_1271 );

    SC_METHOD(thread_tmp_58_fu_851_p1);
    sensitive << ( tmp_57_fu_842_p4 );

    SC_METHOD(thread_tmp_59_fu_855_p4);
    sensitive << ( mt7_7_fu_836_p2 );

    SC_METHOD(thread_tmp_5_fu_268_p3);
    sensitive << ( tmp_14_fu_226_p3 );
    sensitive << ( tmp_4_fu_258_p4 );
    sensitive << ( tmp_2_fu_254_p1 );

    SC_METHOD(thread_tmp_60_fu_865_p3);
    sensitive << ( tmp_50_reg_1226 );
    sensitive << ( tmp_59_fu_855_p4 );
    sensitive << ( tmp_58_fu_851_p1 );

    SC_METHOD(thread_tmp_62_fu_896_p4);
    sensitive << ( p_Val2_4_7_fu_876_p2 );

    SC_METHOD(thread_tmp_63_fu_906_p1);
    sensitive << ( tmp_62_fu_896_p4 );

    SC_METHOD(thread_tmp_64_fu_910_p4);
    sensitive << ( mt_8_fu_890_p2 );

    SC_METHOD(thread_tmp_65_fu_920_p3);
    sensitive << ( tmp_61_reg_1232 );
    sensitive << ( tmp_64_fu_910_p4 );
    sensitive << ( tmp_63_fu_906_p1 );

    SC_METHOD(thread_tmp_66_fu_941_p4);
    sensitive << ( p_Val2_7_7_fu_881_p2 );

    SC_METHOD(thread_tmp_67_fu_951_p1);
    sensitive << ( tmp_66_fu_941_p4 );

    SC_METHOD(thread_tmp_68_fu_955_p4);
    sensitive << ( mt7_8_fu_935_p2 );

    SC_METHOD(thread_tmp_69_fu_965_p3);
    sensitive << ( tmp_61_reg_1232 );
    sensitive << ( tmp_68_fu_955_p4 );
    sensitive << ( tmp_67_fu_951_p1 );

    SC_METHOD(thread_tmp_6_fu_276_p1);
    sensitive << ( tmp_5_fu_268_p3 );

    SC_METHOD(thread_tmp_71_fu_997_p4);
    sensitive << ( p_Val2_4_8_reg_1278 );

    SC_METHOD(thread_tmp_72_fu_1006_p1);
    sensitive << ( tmp_71_fu_997_p4 );

    SC_METHOD(thread_tmp_73_fu_1010_p4);
    sensitive << ( mt_9_fu_991_p2 );

    SC_METHOD(thread_tmp_74_fu_1020_p3);
    sensitive << ( tmp_70_reg_1238 );
    sensitive << ( tmp_73_fu_1010_p4 );
    sensitive << ( tmp_72_fu_1006_p1 );

    SC_METHOD(thread_tmp_75_fu_1040_p4);
    sensitive << ( p_Val2_7_8_reg_1285 );

    SC_METHOD(thread_tmp_76_fu_1049_p1);
    sensitive << ( tmp_75_fu_1040_p4 );

    SC_METHOD(thread_tmp_77_fu_1053_p4);
    sensitive << ( mt7_9_fu_1034_p2 );

    SC_METHOD(thread_tmp_78_fu_1063_p3);
    sensitive << ( tmp_70_reg_1238 );
    sensitive << ( tmp_77_fu_1053_p4 );
    sensitive << ( tmp_76_fu_1049_p1 );

    SC_METHOD(thread_tmp_7_fu_286_p4);
    sensitive << ( mt7_2_fu_280_p2 );

    SC_METHOD(thread_tmp_80_fu_1094_p4);
    sensitive << ( p_Val2_4_9_fu_1074_p2 );

    SC_METHOD(thread_tmp_81_fu_1104_p1);
    sensitive << ( tmp_80_fu_1094_p4 );

    SC_METHOD(thread_tmp_82_fu_1108_p4);
    sensitive << ( mt_s_fu_1088_p2 );

    SC_METHOD(thread_tmp_83_fu_1118_p3);
    sensitive << ( tmp_79_reg_1244 );
    sensitive << ( tmp_82_fu_1108_p4 );
    sensitive << ( tmp_81_fu_1104_p1 );

    SC_METHOD(thread_tmp_84_fu_1139_p4);
    sensitive << ( p_Val2_7_9_fu_1079_p2 );

    SC_METHOD(thread_tmp_85_fu_1149_p1);
    sensitive << ( tmp_84_fu_1139_p4 );

    SC_METHOD(thread_tmp_86_fu_1153_p4);
    sensitive << ( mt7_s_fu_1133_p2 );

    SC_METHOD(thread_tmp_87_fu_1163_p3);
    sensitive << ( tmp_79_reg_1244 );
    sensitive << ( tmp_86_fu_1153_p4 );
    sensitive << ( tmp_85_fu_1149_p1 );

    SC_METHOD(thread_tmp_8_fu_296_p4);
    sensitive << ( p_Val2_7_1_fu_210_p2 );

    SC_METHOD(thread_tmp_9_fu_314_p1);
    sensitive << ( tmp_10_fu_306_p3 );

    SC_METHOD(thread_tmp_fu_244_p4);
    sensitive << ( p_Val2_4_1_fu_200_p2 );

    SC_METHOD(thread_tmp_s_fu_473_p1);
    sensitive << ( tmp_16_v_fu_466_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordic_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, theta_V, "(port)theta_V");
    sc_trace(mVcdFile, s_V, "(port)s_V");
    sc_trace(mVcdFile, s_V_ap_vld, "(port)s_V_ap_vld");
    sc_trace(mVcdFile, c_V, "(port)c_V");
    sc_trace(mVcdFile, c_V_ap_vld, "(port)c_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_Val2_4_2_fu_318_p2, "p_Val2_4_2_fu_318_p2");
    sc_trace(mVcdFile, p_Val2_4_2_reg_1188, "p_Val2_4_2_reg_1188");
    sc_trace(mVcdFile, p_Val2_7_2_fu_324_p2, "p_Val2_7_2_fu_324_p2");
    sc_trace(mVcdFile, p_Val2_7_2_reg_1195, "p_Val2_7_2_reg_1195");
    sc_trace(mVcdFile, tmp_16_reg_1202, "tmp_16_reg_1202");
    sc_trace(mVcdFile, tmp_22_reg_1208, "tmp_22_reg_1208");
    sc_trace(mVcdFile, tmp_29_reg_1214, "tmp_29_reg_1214");
    sc_trace(mVcdFile, tmp_37_reg_1220, "tmp_37_reg_1220");
    sc_trace(mVcdFile, tmp_50_reg_1226, "tmp_50_reg_1226");
    sc_trace(mVcdFile, tmp_61_reg_1232, "tmp_61_reg_1232");
    sc_trace(mVcdFile, tmp_70_reg_1238, "tmp_70_reg_1238");
    sc_trace(mVcdFile, tmp_79_reg_1244, "tmp_79_reg_1244");
    sc_trace(mVcdFile, p_Val2_4_4_fu_596_p2, "p_Val2_4_4_fu_596_p2");
    sc_trace(mVcdFile, p_Val2_4_4_reg_1250, "p_Val2_4_4_reg_1250");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, p_Val2_7_4_fu_602_p2, "p_Val2_7_4_fu_602_p2");
    sc_trace(mVcdFile, p_Val2_7_4_reg_1257, "p_Val2_7_4_reg_1257");
    sc_trace(mVcdFile, p_Val2_4_6_fu_778_p2, "p_Val2_4_6_fu_778_p2");
    sc_trace(mVcdFile, p_Val2_4_6_reg_1264, "p_Val2_4_6_reg_1264");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, p_Val2_7_6_fu_784_p2, "p_Val2_7_6_fu_784_p2");
    sc_trace(mVcdFile, p_Val2_7_6_reg_1271, "p_Val2_7_6_reg_1271");
    sc_trace(mVcdFile, p_Val2_4_8_fu_976_p2, "p_Val2_4_8_fu_976_p2");
    sc_trace(mVcdFile, p_Val2_4_8_reg_1278, "p_Val2_4_8_reg_1278");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, p_Val2_7_8_fu_982_p2, "p_Val2_7_8_fu_982_p2");
    sc_trace(mVcdFile, p_Val2_7_8_reg_1285, "p_Val2_7_8_reg_1285");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_1_fu_130_p3, "tmp_1_fu_130_p3");
    sc_trace(mVcdFile, p_Val2_s_fu_146_p2, "p_Val2_s_fu_146_p2");
    sc_trace(mVcdFile, tmp_13_fu_160_p3, "tmp_13_fu_160_p3");
    sc_trace(mVcdFile, tmp_3_fu_152_p3, "tmp_3_fu_152_p3");
    sc_trace(mVcdFile, mt7_1_fu_184_p3, "mt7_1_fu_184_p3");
    sc_trace(mVcdFile, OP1_V_2_1_fu_176_p3, "OP1_V_2_1_fu_176_p3");
    sc_trace(mVcdFile, r_V_1_1_fu_192_p3, "r_V_1_1_fu_192_p3");
    sc_trace(mVcdFile, p_Val2_4_1_fu_200_p2, "p_Val2_4_1_fu_200_p2");
    sc_trace(mVcdFile, tmp_4_cast_cast_fu_168_p3, "tmp_4_cast_cast_fu_168_p3");
    sc_trace(mVcdFile, p_Val2_7_fu_138_p3, "p_Val2_7_fu_138_p3");
    sc_trace(mVcdFile, p_Val2_7_1_fu_210_p2, "p_Val2_7_1_fu_210_p2");
    sc_trace(mVcdFile, p_Val2_10_1_fu_220_p2, "p_Val2_10_1_fu_220_p2");
    sc_trace(mVcdFile, OP1_V_cast_fu_234_p1, "OP1_V_cast_fu_234_p1");
    sc_trace(mVcdFile, tmp_fu_244_p4, "tmp_fu_244_p4");
    sc_trace(mVcdFile, mt_2_fu_238_p2, "mt_2_fu_238_p2");
    sc_trace(mVcdFile, tmp_14_fu_226_p3, "tmp_14_fu_226_p3");
    sc_trace(mVcdFile, tmp_4_fu_258_p4, "tmp_4_fu_258_p4");
    sc_trace(mVcdFile, tmp_2_fu_254_p1, "tmp_2_fu_254_p1");
    sc_trace(mVcdFile, tmp_5_fu_268_p3, "tmp_5_fu_268_p3");
    sc_trace(mVcdFile, mt7_2_fu_280_p2, "mt7_2_fu_280_p2");
    sc_trace(mVcdFile, tmp_7_fu_286_p4, "tmp_7_fu_286_p4");
    sc_trace(mVcdFile, tmp_8_fu_296_p4, "tmp_8_fu_296_p4");
    sc_trace(mVcdFile, tmp_10_fu_306_p3, "tmp_10_fu_306_p3");
    sc_trace(mVcdFile, p_Val2_4_1_cast_fu_206_p1, "p_Val2_4_1_cast_fu_206_p1");
    sc_trace(mVcdFile, tmp_9_fu_314_p1, "tmp_9_fu_314_p1");
    sc_trace(mVcdFile, tmp_6_fu_276_p1, "tmp_6_fu_276_p1");
    sc_trace(mVcdFile, p_Val2_7_1_cast_fu_216_p1, "p_Val2_7_1_cast_fu_216_p1");
    sc_trace(mVcdFile, p_Val2_10_2_fu_330_p2, "p_Val2_10_2_fu_330_p2");
    sc_trace(mVcdFile, p_Val2_10_3_fu_344_p2, "p_Val2_10_3_fu_344_p2");
    sc_trace(mVcdFile, p_Val2_10_4_fu_358_p2, "p_Val2_10_4_fu_358_p2");
    sc_trace(mVcdFile, p_Val2_10_5_fu_372_p2, "p_Val2_10_5_fu_372_p2");
    sc_trace(mVcdFile, p_Val2_10_6_fu_386_p2, "p_Val2_10_6_fu_386_p2");
    sc_trace(mVcdFile, p_Val2_10_7_fu_400_p2, "p_Val2_10_7_fu_400_p2");
    sc_trace(mVcdFile, p_Val2_10_8_fu_414_p2, "p_Val2_10_8_fu_414_p2");
    sc_trace(mVcdFile, p_Val2_10_9_fu_428_p2, "p_Val2_10_9_fu_428_p2");
    sc_trace(mVcdFile, mt_3_fu_442_p2, "mt_3_fu_442_p2");
    sc_trace(mVcdFile, tmp_19_fu_456_p4, "tmp_19_fu_456_p4");
    sc_trace(mVcdFile, tmp_11_fu_447_p4, "tmp_11_fu_447_p4");
    sc_trace(mVcdFile, tmp_16_v_fu_466_p3, "tmp_16_v_fu_466_p3");
    sc_trace(mVcdFile, mt7_3_fu_477_p2, "mt7_3_fu_477_p2");
    sc_trace(mVcdFile, tmp_20_fu_491_p4, "tmp_20_fu_491_p4");
    sc_trace(mVcdFile, tmp_17_fu_482_p4, "tmp_17_fu_482_p4");
    sc_trace(mVcdFile, tmp_22_v_fu_501_p3, "tmp_22_v_fu_501_p3");
    sc_trace(mVcdFile, tmp_12_fu_508_p1, "tmp_12_fu_508_p1");
    sc_trace(mVcdFile, tmp_s_fu_473_p1, "tmp_s_fu_473_p1");
    sc_trace(mVcdFile, p_Val2_4_3_fu_512_p2, "p_Val2_4_3_fu_512_p2");
    sc_trace(mVcdFile, mt_4_fu_522_p2, "mt_4_fu_522_p2");
    sc_trace(mVcdFile, tmp_25_fu_538_p4, "tmp_25_fu_538_p4");
    sc_trace(mVcdFile, tmp_23_fu_528_p4, "tmp_23_fu_528_p4");
    sc_trace(mVcdFile, tmp_28_v_fu_548_p3, "tmp_28_v_fu_548_p3");
    sc_trace(mVcdFile, p_Val2_7_3_fu_517_p2, "p_Val2_7_3_fu_517_p2");
    sc_trace(mVcdFile, mt7_4_fu_559_p2, "mt7_4_fu_559_p2");
    sc_trace(mVcdFile, tmp_28_fu_575_p4, "tmp_28_fu_575_p4");
    sc_trace(mVcdFile, tmp_26_fu_565_p4, "tmp_26_fu_565_p4");
    sc_trace(mVcdFile, tmp_34_v_fu_585_p3, "tmp_34_v_fu_585_p3");
    sc_trace(mVcdFile, tmp_18_fu_592_p1, "tmp_18_fu_592_p1");
    sc_trace(mVcdFile, tmp_15_fu_555_p1, "tmp_15_fu_555_p1");
    sc_trace(mVcdFile, mt_5_fu_608_p2, "mt_5_fu_608_p2");
    sc_trace(mVcdFile, tmp_32_fu_622_p4, "tmp_32_fu_622_p4");
    sc_trace(mVcdFile, tmp_31_fu_613_p4, "tmp_31_fu_613_p4");
    sc_trace(mVcdFile, tmp_40_v_fu_632_p3, "tmp_40_v_fu_632_p3");
    sc_trace(mVcdFile, mt7_5_fu_643_p2, "mt7_5_fu_643_p2");
    sc_trace(mVcdFile, tmp_35_fu_657_p4, "tmp_35_fu_657_p4");
    sc_trace(mVcdFile, tmp_34_fu_648_p4, "tmp_34_fu_648_p4");
    sc_trace(mVcdFile, tmp_46_v_fu_667_p3, "tmp_46_v_fu_667_p3");
    sc_trace(mVcdFile, tmp_24_fu_674_p1, "tmp_24_fu_674_p1");
    sc_trace(mVcdFile, tmp_21_fu_639_p1, "tmp_21_fu_639_p1");
    sc_trace(mVcdFile, p_Val2_4_5_fu_678_p2, "p_Val2_4_5_fu_678_p2");
    sc_trace(mVcdFile, OP1_V_6_cast_fu_688_p1, "OP1_V_6_cast_fu_688_p1");
    sc_trace(mVcdFile, tmp_38_fu_698_p4, "tmp_38_fu_698_p4");
    sc_trace(mVcdFile, mt_6_fu_692_p2, "mt_6_fu_692_p2");
    sc_trace(mVcdFile, tmp_41_fu_712_p4, "tmp_41_fu_712_p4");
    sc_trace(mVcdFile, tmp_40_fu_708_p1, "tmp_40_fu_708_p1");
    sc_trace(mVcdFile, tmp_43_fu_722_p3, "tmp_43_fu_722_p3");
    sc_trace(mVcdFile, p_Val2_7_5_fu_683_p2, "p_Val2_7_5_fu_683_p2");
    sc_trace(mVcdFile, OP1_V_2_6_cast_fu_733_p1, "OP1_V_2_6_cast_fu_733_p1");
    sc_trace(mVcdFile, tmp_44_fu_743_p4, "tmp_44_fu_743_p4");
    sc_trace(mVcdFile, mt7_6_fu_737_p2, "mt7_6_fu_737_p2");
    sc_trace(mVcdFile, tmp_47_fu_757_p4, "tmp_47_fu_757_p4");
    sc_trace(mVcdFile, tmp_46_fu_753_p1, "tmp_46_fu_753_p1");
    sc_trace(mVcdFile, tmp_49_fu_767_p3, "tmp_49_fu_767_p3");
    sc_trace(mVcdFile, tmp_30_fu_774_p1, "tmp_30_fu_774_p1");
    sc_trace(mVcdFile, tmp_27_fu_729_p1, "tmp_27_fu_729_p1");
    sc_trace(mVcdFile, OP1_V_7_cast_fu_790_p1, "OP1_V_7_cast_fu_790_p1");
    sc_trace(mVcdFile, tmp_52_fu_799_p4, "tmp_52_fu_799_p4");
    sc_trace(mVcdFile, mt_7_fu_793_p2, "mt_7_fu_793_p2");
    sc_trace(mVcdFile, tmp_55_fu_812_p4, "tmp_55_fu_812_p4");
    sc_trace(mVcdFile, tmp_53_fu_808_p1, "tmp_53_fu_808_p1");
    sc_trace(mVcdFile, tmp_56_fu_822_p3, "tmp_56_fu_822_p3");
    sc_trace(mVcdFile, OP1_V_2_7_cast_fu_833_p1, "OP1_V_2_7_cast_fu_833_p1");
    sc_trace(mVcdFile, tmp_57_fu_842_p4, "tmp_57_fu_842_p4");
    sc_trace(mVcdFile, mt7_7_fu_836_p2, "mt7_7_fu_836_p2");
    sc_trace(mVcdFile, tmp_59_fu_855_p4, "tmp_59_fu_855_p4");
    sc_trace(mVcdFile, tmp_58_fu_851_p1, "tmp_58_fu_851_p1");
    sc_trace(mVcdFile, tmp_60_fu_865_p3, "tmp_60_fu_865_p3");
    sc_trace(mVcdFile, tmp_36_fu_872_p1, "tmp_36_fu_872_p1");
    sc_trace(mVcdFile, tmp_33_fu_829_p1, "tmp_33_fu_829_p1");
    sc_trace(mVcdFile, p_Val2_4_7_fu_876_p2, "p_Val2_4_7_fu_876_p2");
    sc_trace(mVcdFile, OP1_V_8_cast_fu_886_p1, "OP1_V_8_cast_fu_886_p1");
    sc_trace(mVcdFile, tmp_62_fu_896_p4, "tmp_62_fu_896_p4");
    sc_trace(mVcdFile, mt_8_fu_890_p2, "mt_8_fu_890_p2");
    sc_trace(mVcdFile, tmp_64_fu_910_p4, "tmp_64_fu_910_p4");
    sc_trace(mVcdFile, tmp_63_fu_906_p1, "tmp_63_fu_906_p1");
    sc_trace(mVcdFile, tmp_65_fu_920_p3, "tmp_65_fu_920_p3");
    sc_trace(mVcdFile, p_Val2_7_7_fu_881_p2, "p_Val2_7_7_fu_881_p2");
    sc_trace(mVcdFile, OP1_V_2_8_cast_fu_931_p1, "OP1_V_2_8_cast_fu_931_p1");
    sc_trace(mVcdFile, tmp_66_fu_941_p4, "tmp_66_fu_941_p4");
    sc_trace(mVcdFile, mt7_8_fu_935_p2, "mt7_8_fu_935_p2");
    sc_trace(mVcdFile, tmp_68_fu_955_p4, "tmp_68_fu_955_p4");
    sc_trace(mVcdFile, tmp_67_fu_951_p1, "tmp_67_fu_951_p1");
    sc_trace(mVcdFile, tmp_69_fu_965_p3, "tmp_69_fu_965_p3");
    sc_trace(mVcdFile, tmp_42_fu_972_p1, "tmp_42_fu_972_p1");
    sc_trace(mVcdFile, tmp_39_fu_927_p1, "tmp_39_fu_927_p1");
    sc_trace(mVcdFile, OP1_V_9_cast_fu_988_p1, "OP1_V_9_cast_fu_988_p1");
    sc_trace(mVcdFile, tmp_71_fu_997_p4, "tmp_71_fu_997_p4");
    sc_trace(mVcdFile, mt_9_fu_991_p2, "mt_9_fu_991_p2");
    sc_trace(mVcdFile, tmp_73_fu_1010_p4, "tmp_73_fu_1010_p4");
    sc_trace(mVcdFile, tmp_72_fu_1006_p1, "tmp_72_fu_1006_p1");
    sc_trace(mVcdFile, tmp_74_fu_1020_p3, "tmp_74_fu_1020_p3");
    sc_trace(mVcdFile, OP1_V_2_9_cast_fu_1031_p1, "OP1_V_2_9_cast_fu_1031_p1");
    sc_trace(mVcdFile, tmp_75_fu_1040_p4, "tmp_75_fu_1040_p4");
    sc_trace(mVcdFile, mt7_9_fu_1034_p2, "mt7_9_fu_1034_p2");
    sc_trace(mVcdFile, tmp_77_fu_1053_p4, "tmp_77_fu_1053_p4");
    sc_trace(mVcdFile, tmp_76_fu_1049_p1, "tmp_76_fu_1049_p1");
    sc_trace(mVcdFile, tmp_78_fu_1063_p3, "tmp_78_fu_1063_p3");
    sc_trace(mVcdFile, tmp_48_fu_1070_p1, "tmp_48_fu_1070_p1");
    sc_trace(mVcdFile, tmp_45_fu_1027_p1, "tmp_45_fu_1027_p1");
    sc_trace(mVcdFile, p_Val2_4_9_fu_1074_p2, "p_Val2_4_9_fu_1074_p2");
    sc_trace(mVcdFile, OP1_V_2_cast_fu_1084_p1, "OP1_V_2_cast_fu_1084_p1");
    sc_trace(mVcdFile, tmp_80_fu_1094_p4, "tmp_80_fu_1094_p4");
    sc_trace(mVcdFile, mt_s_fu_1088_p2, "mt_s_fu_1088_p2");
    sc_trace(mVcdFile, tmp_82_fu_1108_p4, "tmp_82_fu_1108_p4");
    sc_trace(mVcdFile, tmp_81_fu_1104_p1, "tmp_81_fu_1104_p1");
    sc_trace(mVcdFile, tmp_83_fu_1118_p3, "tmp_83_fu_1118_p3");
    sc_trace(mVcdFile, p_Val2_7_9_fu_1079_p2, "p_Val2_7_9_fu_1079_p2");
    sc_trace(mVcdFile, OP1_V_2_cast_10_fu_1129_p1, "OP1_V_2_cast_10_fu_1129_p1");
    sc_trace(mVcdFile, tmp_84_fu_1139_p4, "tmp_84_fu_1139_p4");
    sc_trace(mVcdFile, mt7_s_fu_1133_p2, "mt7_s_fu_1133_p2");
    sc_trace(mVcdFile, tmp_86_fu_1153_p4, "tmp_86_fu_1153_p4");
    sc_trace(mVcdFile, tmp_85_fu_1149_p1, "tmp_85_fu_1149_p1");
    sc_trace(mVcdFile, tmp_87_fu_1163_p3, "tmp_87_fu_1163_p3");
    sc_trace(mVcdFile, tmp_54_fu_1170_p1, "tmp_54_fu_1170_p1");
    sc_trace(mVcdFile, tmp_51_fu_1125_p1, "tmp_51_fu_1125_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("cordic.hdltvin.dat");
    mHdltvoutHandle.open("cordic.hdltvout.dat");
}

cordic::~cordic() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
}

void cordic::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_4_2_reg_1188 = p_Val2_4_2_fu_318_p2.read();
        p_Val2_7_2_reg_1195 = p_Val2_7_2_fu_324_p2.read();
        tmp_16_reg_1202 = p_Val2_10_2_fu_330_p2.read().range(11, 11);
        tmp_22_reg_1208 = p_Val2_10_3_fu_344_p2.read().range(11, 11);
        tmp_29_reg_1214 = p_Val2_10_4_fu_358_p2.read().range(11, 11);
        tmp_37_reg_1220 = p_Val2_10_5_fu_372_p2.read().range(11, 11);
        tmp_50_reg_1226 = p_Val2_10_6_fu_386_p2.read().range(11, 11);
        tmp_61_reg_1232 = p_Val2_10_7_fu_400_p2.read().range(11, 11);
        tmp_70_reg_1238 = p_Val2_10_8_fu_414_p2.read().range(11, 11);
        tmp_79_reg_1244 = p_Val2_10_9_fu_428_p2.read().range(11, 11);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_Val2_4_4_reg_1250 = p_Val2_4_4_fu_596_p2.read();
        p_Val2_7_4_reg_1257 = p_Val2_7_4_fu_602_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_Val2_4_6_reg_1264 = p_Val2_4_6_fu_778_p2.read();
        p_Val2_7_6_reg_1271 = p_Val2_7_6_fu_784_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        p_Val2_4_8_reg_1278 = p_Val2_4_8_fu_976_p2.read();
        p_Val2_7_8_reg_1285 = p_Val2_7_8_fu_982_p2.read();
    }
}

void cordic::thread_OP1_V_2_1_fu_176_p3() {
    OP1_V_2_1_fu_176_p3 = (!tmp_1_fu_130_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_1_fu_130_p3.read()[0].to_bool())? ap_const_lv10_2C9: ap_const_lv10_136);
}

void cordic::thread_OP1_V_2_6_cast_fu_733_p1() {
    OP1_V_2_6_cast_fu_733_p1 = esl_sext<13,12>(p_Val2_7_5_fu_683_p2.read());
}

void cordic::thread_OP1_V_2_7_cast_fu_833_p1() {
    OP1_V_2_7_cast_fu_833_p1 = esl_sext<13,12>(p_Val2_7_6_reg_1271.read());
}

void cordic::thread_OP1_V_2_8_cast_fu_931_p1() {
    OP1_V_2_8_cast_fu_931_p1 = esl_sext<13,12>(p_Val2_7_7_fu_881_p2.read());
}

void cordic::thread_OP1_V_2_9_cast_fu_1031_p1() {
    OP1_V_2_9_cast_fu_1031_p1 = esl_sext<13,12>(p_Val2_7_8_reg_1285.read());
}

void cordic::thread_OP1_V_2_cast_10_fu_1129_p1() {
    OP1_V_2_cast_10_fu_1129_p1 = esl_sext<13,12>(p_Val2_7_9_fu_1079_p2.read());
}

void cordic::thread_OP1_V_2_cast_fu_1084_p1() {
    OP1_V_2_cast_fu_1084_p1 = esl_sext<13,12>(p_Val2_4_9_fu_1074_p2.read());
}

void cordic::thread_OP1_V_6_cast_fu_688_p1() {
    OP1_V_6_cast_fu_688_p1 = esl_sext<13,12>(p_Val2_4_5_fu_678_p2.read());
}

void cordic::thread_OP1_V_7_cast_fu_790_p1() {
    OP1_V_7_cast_fu_790_p1 = esl_sext<13,12>(p_Val2_4_6_reg_1264.read());
}

void cordic::thread_OP1_V_8_cast_fu_886_p1() {
    OP1_V_8_cast_fu_886_p1 = esl_sext<13,12>(p_Val2_4_7_fu_876_p2.read());
}

void cordic::thread_OP1_V_9_cast_fu_988_p1() {
    OP1_V_9_cast_fu_988_p1 = esl_sext<13,12>(p_Val2_4_8_reg_1278.read());
}

void cordic::thread_OP1_V_cast_fu_234_p1() {
    OP1_V_cast_fu_234_p1 = esl_zext<11,10>(p_Val2_4_1_fu_200_p2.read());
}

void cordic::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordic::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordic::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordic::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cordic::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cordic::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordic::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordic::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordic::thread_c_V() {
    c_V = (!p_Val2_4_9_fu_1074_p2.read().is_01() || !tmp_54_fu_1170_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_9_fu_1074_p2.read()) - sc_bigint<12>(tmp_54_fu_1170_p1.read()));
}

void cordic::thread_c_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        c_V_ap_vld = ap_const_logic_1;
    } else {
        c_V_ap_vld = ap_const_logic_0;
    }
}

void cordic::thread_mt7_1_fu_184_p3() {
    mt7_1_fu_184_p3 = (!tmp_1_fu_130_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_1_fu_130_p3.read()[0].to_bool())? ap_const_lv10_136: ap_const_lv10_2C9);
}

void cordic::thread_mt7_2_fu_280_p2() {
    mt7_2_fu_280_p2 = (!ap_const_lv11_0.is_01() || !p_Val2_7_1_fu_210_p2.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_0) - sc_biguint<11>(p_Val2_7_1_fu_210_p2.read()));
}

void cordic::thread_mt7_3_fu_477_p2() {
    mt7_3_fu_477_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_7_2_reg_1195.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_7_2_reg_1195.read()));
}

void cordic::thread_mt7_4_fu_559_p2() {
    mt7_4_fu_559_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_7_3_fu_517_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_7_3_fu_517_p2.read()));
}

void cordic::thread_mt7_5_fu_643_p2() {
    mt7_5_fu_643_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_7_4_reg_1257.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_7_4_reg_1257.read()));
}

void cordic::thread_mt7_6_fu_737_p2() {
    mt7_6_fu_737_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_6_cast_fu_733_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_6_cast_fu_733_p1.read()));
}

void cordic::thread_mt7_7_fu_836_p2() {
    mt7_7_fu_836_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_7_cast_fu_833_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_7_cast_fu_833_p1.read()));
}

void cordic::thread_mt7_8_fu_935_p2() {
    mt7_8_fu_935_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_8_cast_fu_931_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_8_cast_fu_931_p1.read()));
}

void cordic::thread_mt7_9_fu_1034_p2() {
    mt7_9_fu_1034_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_9_cast_fu_1031_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_9_cast_fu_1031_p1.read()));
}

void cordic::thread_mt7_s_fu_1133_p2() {
    mt7_s_fu_1133_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_cast_10_fu_1129_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_cast_10_fu_1129_p1.read()));
}

void cordic::thread_mt_2_fu_238_p2() {
    mt_2_fu_238_p2 = (!ap_const_lv11_0.is_01() || !OP1_V_cast_fu_234_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_0) - sc_biguint<11>(OP1_V_cast_fu_234_p1.read()));
}

void cordic::thread_mt_3_fu_442_p2() {
    mt_3_fu_442_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_4_2_reg_1188.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_4_2_reg_1188.read()));
}

void cordic::thread_mt_4_fu_522_p2() {
    mt_4_fu_522_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_4_3_fu_512_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_4_3_fu_512_p2.read()));
}

void cordic::thread_mt_5_fu_608_p2() {
    mt_5_fu_608_p2 = (!ap_const_lv12_0.is_01() || !p_Val2_4_4_reg_1250.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(p_Val2_4_4_reg_1250.read()));
}

void cordic::thread_mt_6_fu_692_p2() {
    mt_6_fu_692_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_6_cast_fu_688_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_6_cast_fu_688_p1.read()));
}

void cordic::thread_mt_7_fu_793_p2() {
    mt_7_fu_793_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_7_cast_fu_790_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_7_cast_fu_790_p1.read()));
}

void cordic::thread_mt_8_fu_890_p2() {
    mt_8_fu_890_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_8_cast_fu_886_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_8_cast_fu_886_p1.read()));
}

void cordic::thread_mt_9_fu_991_p2() {
    mt_9_fu_991_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_9_cast_fu_988_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_9_cast_fu_988_p1.read()));
}

void cordic::thread_mt_s_fu_1088_p2() {
    mt_s_fu_1088_p2 = (!ap_const_lv13_0.is_01() || !OP1_V_2_cast_fu_1084_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(OP1_V_2_cast_fu_1084_p1.read()));
}

void cordic::thread_p_Val2_10_1_fu_220_p2() {
    p_Val2_10_1_fu_220_p2 = (!theta_V.read().is_01() || !ap_const_lv12_B02.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_B02));
}

void cordic::thread_p_Val2_10_2_fu_330_p2() {
    p_Val2_10_2_fu_330_p2 = (!theta_V.read().is_01() || !ap_const_lv12_A08.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_A08));
}

void cordic::thread_p_Val2_10_3_fu_344_p2() {
    p_Val2_10_3_fu_344_p2 = (!theta_V.read().is_01() || !ap_const_lv12_989.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_989));
}

void cordic::thread_p_Val2_10_4_fu_358_p2() {
    p_Val2_10_4_fu_358_p2 = (!theta_V.read().is_01() || !ap_const_lv12_94A.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_94A));
}

void cordic::thread_p_Val2_10_5_fu_372_p2() {
    p_Val2_10_5_fu_372_p2 = (!theta_V.read().is_01() || !ap_const_lv12_92B.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_92B));
}

void cordic::thread_p_Val2_10_6_fu_386_p2() {
    p_Val2_10_6_fu_386_p2 = (!theta_V.read().is_01() || !ap_const_lv12_91C.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_91C));
}

void cordic::thread_p_Val2_10_7_fu_400_p2() {
    p_Val2_10_7_fu_400_p2 = (!theta_V.read().is_01() || !ap_const_lv12_915.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_915));
}

void cordic::thread_p_Val2_10_8_fu_414_p2() {
    p_Val2_10_8_fu_414_p2 = (!theta_V.read().is_01() || !ap_const_lv12_912.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_912));
}

void cordic::thread_p_Val2_10_9_fu_428_p2() {
    p_Val2_10_9_fu_428_p2 = (!theta_V.read().is_01() || !ap_const_lv12_911.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_911));
}

void cordic::thread_p_Val2_4_1_cast_fu_206_p1() {
    p_Val2_4_1_cast_fu_206_p1 = esl_zext<12,10>(p_Val2_4_1_fu_200_p2.read());
}

void cordic::thread_p_Val2_4_1_fu_200_p2() {
    p_Val2_4_1_fu_200_p2 = (!ap_const_lv10_26D.is_01() || !r_V_1_1_fu_192_p3.read().is_01())? sc_lv<10>(): (sc_bigint<10>(ap_const_lv10_26D) - sc_biguint<10>(r_V_1_1_fu_192_p3.read()));
}

void cordic::thread_p_Val2_4_2_fu_318_p2() {
    p_Val2_4_2_fu_318_p2 = (!p_Val2_4_1_cast_fu_206_p1.read().is_01() || !tmp_9_fu_314_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_1_cast_fu_206_p1.read()) - sc_bigint<12>(tmp_9_fu_314_p1.read()));
}

void cordic::thread_p_Val2_4_3_fu_512_p2() {
    p_Val2_4_3_fu_512_p2 = (!p_Val2_4_2_reg_1188.read().is_01() || !tmp_12_fu_508_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_2_reg_1188.read()) - sc_bigint<12>(tmp_12_fu_508_p1.read()));
}

void cordic::thread_p_Val2_4_4_fu_596_p2() {
    p_Val2_4_4_fu_596_p2 = (!p_Val2_4_3_fu_512_p2.read().is_01() || !tmp_18_fu_592_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_3_fu_512_p2.read()) - sc_bigint<12>(tmp_18_fu_592_p1.read()));
}

void cordic::thread_p_Val2_4_5_fu_678_p2() {
    p_Val2_4_5_fu_678_p2 = (!p_Val2_4_4_reg_1250.read().is_01() || !tmp_24_fu_674_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_4_reg_1250.read()) - sc_bigint<12>(tmp_24_fu_674_p1.read()));
}

void cordic::thread_p_Val2_4_6_fu_778_p2() {
    p_Val2_4_6_fu_778_p2 = (!p_Val2_4_5_fu_678_p2.read().is_01() || !tmp_30_fu_774_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_5_fu_678_p2.read()) - sc_bigint<12>(tmp_30_fu_774_p1.read()));
}

void cordic::thread_p_Val2_4_7_fu_876_p2() {
    p_Val2_4_7_fu_876_p2 = (!p_Val2_4_6_reg_1264.read().is_01() || !tmp_36_fu_872_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_6_reg_1264.read()) - sc_bigint<12>(tmp_36_fu_872_p1.read()));
}

void cordic::thread_p_Val2_4_8_fu_976_p2() {
    p_Val2_4_8_fu_976_p2 = (!p_Val2_4_7_fu_876_p2.read().is_01() || !tmp_42_fu_972_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_7_fu_876_p2.read()) - sc_bigint<12>(tmp_42_fu_972_p1.read()));
}

void cordic::thread_p_Val2_4_9_fu_1074_p2() {
    p_Val2_4_9_fu_1074_p2 = (!p_Val2_4_8_reg_1278.read().is_01() || !tmp_48_fu_1070_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_Val2_4_8_reg_1278.read()) - sc_bigint<12>(tmp_48_fu_1070_p1.read()));
}

void cordic::thread_p_Val2_7_1_cast_fu_216_p1() {
    p_Val2_7_1_cast_fu_216_p1 = esl_sext<12,11>(p_Val2_7_1_fu_210_p2.read());
}

void cordic::thread_p_Val2_7_1_fu_210_p2() {
    p_Val2_7_1_fu_210_p2 = (!tmp_4_cast_cast_fu_168_p3.read().is_01() || !p_Val2_7_fu_138_p3.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_4_cast_cast_fu_168_p3.read()) + sc_biguint<11>(p_Val2_7_fu_138_p3.read()));
}

void cordic::thread_p_Val2_7_2_fu_324_p2() {
    p_Val2_7_2_fu_324_p2 = (!tmp_6_fu_276_p1.read().is_01() || !p_Val2_7_1_cast_fu_216_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_6_fu_276_p1.read()) + sc_bigint<12>(p_Val2_7_1_cast_fu_216_p1.read()));
}

void cordic::thread_p_Val2_7_3_fu_517_p2() {
    p_Val2_7_3_fu_517_p2 = (!tmp_s_fu_473_p1.read().is_01() || !p_Val2_7_2_reg_1195.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_s_fu_473_p1.read()) + sc_biguint<12>(p_Val2_7_2_reg_1195.read()));
}

void cordic::thread_p_Val2_7_4_fu_602_p2() {
    p_Val2_7_4_fu_602_p2 = (!tmp_15_fu_555_p1.read().is_01() || !p_Val2_7_3_fu_517_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_15_fu_555_p1.read()) + sc_biguint<12>(p_Val2_7_3_fu_517_p2.read()));
}

void cordic::thread_p_Val2_7_5_fu_683_p2() {
    p_Val2_7_5_fu_683_p2 = (!tmp_21_fu_639_p1.read().is_01() || !p_Val2_7_4_reg_1257.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_21_fu_639_p1.read()) + sc_biguint<12>(p_Val2_7_4_reg_1257.read()));
}

void cordic::thread_p_Val2_7_6_fu_784_p2() {
    p_Val2_7_6_fu_784_p2 = (!tmp_27_fu_729_p1.read().is_01() || !p_Val2_7_5_fu_683_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_27_fu_729_p1.read()) + sc_biguint<12>(p_Val2_7_5_fu_683_p2.read()));
}

void cordic::thread_p_Val2_7_7_fu_881_p2() {
    p_Val2_7_7_fu_881_p2 = (!tmp_33_fu_829_p1.read().is_01() || !p_Val2_7_6_reg_1271.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_33_fu_829_p1.read()) + sc_biguint<12>(p_Val2_7_6_reg_1271.read()));
}

void cordic::thread_p_Val2_7_8_fu_982_p2() {
    p_Val2_7_8_fu_982_p2 = (!tmp_39_fu_927_p1.read().is_01() || !p_Val2_7_7_fu_881_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_39_fu_927_p1.read()) + sc_biguint<12>(p_Val2_7_7_fu_881_p2.read()));
}

void cordic::thread_p_Val2_7_9_fu_1079_p2() {
    p_Val2_7_9_fu_1079_p2 = (!tmp_45_fu_1027_p1.read().is_01() || !p_Val2_7_8_reg_1285.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_45_fu_1027_p1.read()) + sc_biguint<12>(p_Val2_7_8_reg_1285.read()));
}

void cordic::thread_p_Val2_7_fu_138_p3() {
    p_Val2_7_fu_138_p3 = (!tmp_1_fu_130_p3.read()[0].is_01())? sc_lv<11>(): ((tmp_1_fu_130_p3.read()[0].to_bool())? ap_const_lv11_593: ap_const_lv11_26D);
}

void cordic::thread_p_Val2_s_fu_146_p2() {
    p_Val2_s_fu_146_p2 = (!theta_V.read().is_01() || !ap_const_lv12_CDC.is_01())? sc_lv<12>(): (sc_biguint<12>(theta_V.read()) + sc_bigint<12>(ap_const_lv12_CDC));
}

void cordic::thread_r_V_1_1_fu_192_p3() {
    r_V_1_1_fu_192_p3 = (!tmp_3_fu_152_p3.read()[0].is_01())? sc_lv<10>(): ((tmp_3_fu_152_p3.read()[0].to_bool())? mt7_1_fu_184_p3.read(): OP1_V_2_1_fu_176_p3.read());
}

void cordic::thread_s_V() {
    s_V = (!tmp_51_fu_1125_p1.read().is_01() || !p_Val2_7_9_fu_1079_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(tmp_51_fu_1125_p1.read()) + sc_biguint<12>(p_Val2_7_9_fu_1079_p2.read()));
}

void cordic::thread_s_V_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        s_V_ap_vld = ap_const_logic_1;
    } else {
        s_V_ap_vld = ap_const_logic_0;
    }
}

void cordic::thread_tmp_10_fu_306_p3() {
    tmp_10_fu_306_p3 = (!tmp_14_fu_226_p3.read()[0].is_01())? sc_lv<9>(): ((tmp_14_fu_226_p3.read()[0].to_bool())? tmp_7_fu_286_p4.read(): tmp_8_fu_296_p4.read());
}

void cordic::thread_tmp_11_fu_447_p4() {
    tmp_11_fu_447_p4 = p_Val2_4_2_reg_1188.read().range(11, 3);
}

void cordic::thread_tmp_12_fu_508_p1() {
    tmp_12_fu_508_p1 = esl_sext<12,9>(tmp_22_v_fu_501_p3.read());
}

void cordic::thread_tmp_13_fu_160_p3() {
    tmp_13_fu_160_p3 = p_Val2_s_fu_146_p2.read().range(11, 11);
}

void cordic::thread_tmp_14_fu_226_p3() {
    tmp_14_fu_226_p3 = p_Val2_10_1_fu_220_p2.read().range(11, 11);
}

void cordic::thread_tmp_15_fu_555_p1() {
    tmp_15_fu_555_p1 = esl_sext<12,8>(tmp_28_v_fu_548_p3.read());
}

void cordic::thread_tmp_16_v_fu_466_p3() {
    tmp_16_v_fu_466_p3 = (!tmp_16_reg_1202.read()[0].is_01())? sc_lv<9>(): ((tmp_16_reg_1202.read()[0].to_bool())? tmp_19_fu_456_p4.read(): tmp_11_fu_447_p4.read());
}

void cordic::thread_tmp_17_fu_482_p4() {
    tmp_17_fu_482_p4 = p_Val2_7_2_reg_1195.read().range(11, 3);
}

void cordic::thread_tmp_18_fu_592_p1() {
    tmp_18_fu_592_p1 = esl_sext<12,8>(tmp_34_v_fu_585_p3.read());
}

void cordic::thread_tmp_19_fu_456_p4() {
    tmp_19_fu_456_p4 = mt_3_fu_442_p2.read().range(11, 3);
}

void cordic::thread_tmp_1_fu_130_p3() {
    tmp_1_fu_130_p3 = theta_V.read().range(11, 11);
}

void cordic::thread_tmp_20_fu_491_p4() {
    tmp_20_fu_491_p4 = mt7_3_fu_477_p2.read().range(11, 3);
}

void cordic::thread_tmp_21_fu_639_p1() {
    tmp_21_fu_639_p1 = esl_sext<12,7>(tmp_40_v_fu_632_p3.read());
}

void cordic::thread_tmp_22_v_fu_501_p3() {
    tmp_22_v_fu_501_p3 = (!tmp_16_reg_1202.read()[0].is_01())? sc_lv<9>(): ((tmp_16_reg_1202.read()[0].to_bool())? tmp_20_fu_491_p4.read(): tmp_17_fu_482_p4.read());
}

void cordic::thread_tmp_23_fu_528_p4() {
    tmp_23_fu_528_p4 = p_Val2_4_3_fu_512_p2.read().range(11, 4);
}

void cordic::thread_tmp_24_fu_674_p1() {
    tmp_24_fu_674_p1 = esl_sext<12,7>(tmp_46_v_fu_667_p3.read());
}

void cordic::thread_tmp_25_fu_538_p4() {
    tmp_25_fu_538_p4 = mt_4_fu_522_p2.read().range(11, 4);
}

void cordic::thread_tmp_26_fu_565_p4() {
    tmp_26_fu_565_p4 = p_Val2_7_3_fu_517_p2.read().range(11, 4);
}

void cordic::thread_tmp_27_fu_729_p1() {
    tmp_27_fu_729_p1 = esl_sext<12,7>(tmp_43_fu_722_p3.read());
}

void cordic::thread_tmp_28_fu_575_p4() {
    tmp_28_fu_575_p4 = mt7_4_fu_559_p2.read().range(11, 4);
}

void cordic::thread_tmp_28_v_fu_548_p3() {
    tmp_28_v_fu_548_p3 = (!tmp_22_reg_1208.read()[0].is_01())? sc_lv<8>(): ((tmp_22_reg_1208.read()[0].to_bool())? tmp_25_fu_538_p4.read(): tmp_23_fu_528_p4.read());
}

void cordic::thread_tmp_2_fu_254_p1() {
    tmp_2_fu_254_p1 = esl_zext<9,8>(tmp_fu_244_p4.read());
}

void cordic::thread_tmp_30_fu_774_p1() {
    tmp_30_fu_774_p1 = esl_sext<12,7>(tmp_49_fu_767_p3.read());
}

void cordic::thread_tmp_31_fu_613_p4() {
    tmp_31_fu_613_p4 = p_Val2_4_4_reg_1250.read().range(11, 5);
}

void cordic::thread_tmp_32_fu_622_p4() {
    tmp_32_fu_622_p4 = mt_5_fu_608_p2.read().range(11, 5);
}

void cordic::thread_tmp_33_fu_829_p1() {
    tmp_33_fu_829_p1 = esl_sext<12,6>(tmp_56_fu_822_p3.read());
}

void cordic::thread_tmp_34_fu_648_p4() {
    tmp_34_fu_648_p4 = p_Val2_7_4_reg_1257.read().range(11, 5);
}

void cordic::thread_tmp_34_v_fu_585_p3() {
    tmp_34_v_fu_585_p3 = (!tmp_22_reg_1208.read()[0].is_01())? sc_lv<8>(): ((tmp_22_reg_1208.read()[0].to_bool())? tmp_28_fu_575_p4.read(): tmp_26_fu_565_p4.read());
}

void cordic::thread_tmp_35_fu_657_p4() {
    tmp_35_fu_657_p4 = mt7_5_fu_643_p2.read().range(11, 5);
}

void cordic::thread_tmp_36_fu_872_p1() {
    tmp_36_fu_872_p1 = esl_sext<12,6>(tmp_60_fu_865_p3.read());
}

void cordic::thread_tmp_38_fu_698_p4() {
    tmp_38_fu_698_p4 = p_Val2_4_5_fu_678_p2.read().range(11, 6);
}

void cordic::thread_tmp_39_fu_927_p1() {
    tmp_39_fu_927_p1 = esl_sext<12,5>(tmp_65_fu_920_p3.read());
}

void cordic::thread_tmp_3_fu_152_p3() {
    tmp_3_fu_152_p3 = p_Val2_s_fu_146_p2.read().range(11, 11);
}

void cordic::thread_tmp_40_fu_708_p1() {
    tmp_40_fu_708_p1 = esl_sext<7,6>(tmp_38_fu_698_p4.read());
}

void cordic::thread_tmp_40_v_fu_632_p3() {
    tmp_40_v_fu_632_p3 = (!tmp_29_reg_1214.read()[0].is_01())? sc_lv<7>(): ((tmp_29_reg_1214.read()[0].to_bool())? tmp_32_fu_622_p4.read(): tmp_31_fu_613_p4.read());
}

void cordic::thread_tmp_41_fu_712_p4() {
    tmp_41_fu_712_p4 = mt_6_fu_692_p2.read().range(12, 6);
}

void cordic::thread_tmp_42_fu_972_p1() {
    tmp_42_fu_972_p1 = esl_sext<12,5>(tmp_69_fu_965_p3.read());
}

void cordic::thread_tmp_43_fu_722_p3() {
    tmp_43_fu_722_p3 = (!tmp_37_reg_1220.read()[0].is_01())? sc_lv<7>(): ((tmp_37_reg_1220.read()[0].to_bool())? tmp_41_fu_712_p4.read(): tmp_40_fu_708_p1.read());
}

void cordic::thread_tmp_44_fu_743_p4() {
    tmp_44_fu_743_p4 = p_Val2_7_5_fu_683_p2.read().range(11, 6);
}

void cordic::thread_tmp_45_fu_1027_p1() {
    tmp_45_fu_1027_p1 = esl_sext<12,4>(tmp_74_fu_1020_p3.read());
}

void cordic::thread_tmp_46_fu_753_p1() {
    tmp_46_fu_753_p1 = esl_sext<7,6>(tmp_44_fu_743_p4.read());
}

void cordic::thread_tmp_46_v_fu_667_p3() {
    tmp_46_v_fu_667_p3 = (!tmp_29_reg_1214.read()[0].is_01())? sc_lv<7>(): ((tmp_29_reg_1214.read()[0].to_bool())? tmp_35_fu_657_p4.read(): tmp_34_fu_648_p4.read());
}

void cordic::thread_tmp_47_fu_757_p4() {
    tmp_47_fu_757_p4 = mt7_6_fu_737_p2.read().range(12, 6);
}

void cordic::thread_tmp_48_fu_1070_p1() {
    tmp_48_fu_1070_p1 = esl_sext<12,4>(tmp_78_fu_1063_p3.read());
}

void cordic::thread_tmp_49_fu_767_p3() {
    tmp_49_fu_767_p3 = (!tmp_37_reg_1220.read()[0].is_01())? sc_lv<7>(): ((tmp_37_reg_1220.read()[0].to_bool())? tmp_47_fu_757_p4.read(): tmp_46_fu_753_p1.read());
}

void cordic::thread_tmp_4_cast_cast_fu_168_p3() {
    tmp_4_cast_cast_fu_168_p3 = (!tmp_13_fu_160_p3.read()[0].is_01())? sc_lv<11>(): ((tmp_13_fu_160_p3.read()[0].to_bool())? ap_const_lv11_6C9: ap_const_lv11_136);
}

void cordic::thread_tmp_4_fu_258_p4() {
    tmp_4_fu_258_p4 = mt_2_fu_238_p2.read().range(10, 2);
}

void cordic::thread_tmp_51_fu_1125_p1() {
    tmp_51_fu_1125_p1 = esl_sext<12,3>(tmp_83_fu_1118_p3.read());
}

void cordic::thread_tmp_52_fu_799_p4() {
    tmp_52_fu_799_p4 = p_Val2_4_6_reg_1264.read().range(11, 7);
}

void cordic::thread_tmp_53_fu_808_p1() {
    tmp_53_fu_808_p1 = esl_sext<6,5>(tmp_52_fu_799_p4.read());
}

void cordic::thread_tmp_54_fu_1170_p1() {
    tmp_54_fu_1170_p1 = esl_sext<12,3>(tmp_87_fu_1163_p3.read());
}

void cordic::thread_tmp_55_fu_812_p4() {
    tmp_55_fu_812_p4 = mt_7_fu_793_p2.read().range(12, 7);
}

void cordic::thread_tmp_56_fu_822_p3() {
    tmp_56_fu_822_p3 = (!tmp_50_reg_1226.read()[0].is_01())? sc_lv<6>(): ((tmp_50_reg_1226.read()[0].to_bool())? tmp_55_fu_812_p4.read(): tmp_53_fu_808_p1.read());
}

void cordic::thread_tmp_57_fu_842_p4() {
    tmp_57_fu_842_p4 = p_Val2_7_6_reg_1271.read().range(11, 7);
}

void cordic::thread_tmp_58_fu_851_p1() {
    tmp_58_fu_851_p1 = esl_sext<6,5>(tmp_57_fu_842_p4.read());
}

void cordic::thread_tmp_59_fu_855_p4() {
    tmp_59_fu_855_p4 = mt7_7_fu_836_p2.read().range(12, 7);
}

void cordic::thread_tmp_5_fu_268_p3() {
    tmp_5_fu_268_p3 = (!tmp_14_fu_226_p3.read()[0].is_01())? sc_lv<9>(): ((tmp_14_fu_226_p3.read()[0].to_bool())? tmp_4_fu_258_p4.read(): tmp_2_fu_254_p1.read());
}

void cordic::thread_tmp_60_fu_865_p3() {
    tmp_60_fu_865_p3 = (!tmp_50_reg_1226.read()[0].is_01())? sc_lv<6>(): ((tmp_50_reg_1226.read()[0].to_bool())? tmp_59_fu_855_p4.read(): tmp_58_fu_851_p1.read());
}

void cordic::thread_tmp_62_fu_896_p4() {
    tmp_62_fu_896_p4 = p_Val2_4_7_fu_876_p2.read().range(11, 8);
}

void cordic::thread_tmp_63_fu_906_p1() {
    tmp_63_fu_906_p1 = esl_sext<5,4>(tmp_62_fu_896_p4.read());
}

void cordic::thread_tmp_64_fu_910_p4() {
    tmp_64_fu_910_p4 = mt_8_fu_890_p2.read().range(12, 8);
}

void cordic::thread_tmp_65_fu_920_p3() {
    tmp_65_fu_920_p3 = (!tmp_61_reg_1232.read()[0].is_01())? sc_lv<5>(): ((tmp_61_reg_1232.read()[0].to_bool())? tmp_64_fu_910_p4.read(): tmp_63_fu_906_p1.read());
}

void cordic::thread_tmp_66_fu_941_p4() {
    tmp_66_fu_941_p4 = p_Val2_7_7_fu_881_p2.read().range(11, 8);
}

void cordic::thread_tmp_67_fu_951_p1() {
    tmp_67_fu_951_p1 = esl_sext<5,4>(tmp_66_fu_941_p4.read());
}

void cordic::thread_tmp_68_fu_955_p4() {
    tmp_68_fu_955_p4 = mt7_8_fu_935_p2.read().range(12, 8);
}

void cordic::thread_tmp_69_fu_965_p3() {
    tmp_69_fu_965_p3 = (!tmp_61_reg_1232.read()[0].is_01())? sc_lv<5>(): ((tmp_61_reg_1232.read()[0].to_bool())? tmp_68_fu_955_p4.read(): tmp_67_fu_951_p1.read());
}

void cordic::thread_tmp_6_fu_276_p1() {
    tmp_6_fu_276_p1 = esl_sext<12,9>(tmp_5_fu_268_p3.read());
}

void cordic::thread_tmp_71_fu_997_p4() {
    tmp_71_fu_997_p4 = p_Val2_4_8_reg_1278.read().range(11, 9);
}

void cordic::thread_tmp_72_fu_1006_p1() {
    tmp_72_fu_1006_p1 = esl_sext<4,3>(tmp_71_fu_997_p4.read());
}

void cordic::thread_tmp_73_fu_1010_p4() {
    tmp_73_fu_1010_p4 = mt_9_fu_991_p2.read().range(12, 9);
}

void cordic::thread_tmp_74_fu_1020_p3() {
    tmp_74_fu_1020_p3 = (!tmp_70_reg_1238.read()[0].is_01())? sc_lv<4>(): ((tmp_70_reg_1238.read()[0].to_bool())? tmp_73_fu_1010_p4.read(): tmp_72_fu_1006_p1.read());
}

void cordic::thread_tmp_75_fu_1040_p4() {
    tmp_75_fu_1040_p4 = p_Val2_7_8_reg_1285.read().range(11, 9);
}

void cordic::thread_tmp_76_fu_1049_p1() {
    tmp_76_fu_1049_p1 = esl_sext<4,3>(tmp_75_fu_1040_p4.read());
}

void cordic::thread_tmp_77_fu_1053_p4() {
    tmp_77_fu_1053_p4 = mt7_9_fu_1034_p2.read().range(12, 9);
}

void cordic::thread_tmp_78_fu_1063_p3() {
    tmp_78_fu_1063_p3 = (!tmp_70_reg_1238.read()[0].is_01())? sc_lv<4>(): ((tmp_70_reg_1238.read()[0].to_bool())? tmp_77_fu_1053_p4.read(): tmp_76_fu_1049_p1.read());
}

void cordic::thread_tmp_7_fu_286_p4() {
    tmp_7_fu_286_p4 = mt7_2_fu_280_p2.read().range(10, 2);
}

void cordic::thread_tmp_80_fu_1094_p4() {
    tmp_80_fu_1094_p4 = p_Val2_4_9_fu_1074_p2.read().range(11, 10);
}

void cordic::thread_tmp_81_fu_1104_p1() {
    tmp_81_fu_1104_p1 = esl_sext<3,2>(tmp_80_fu_1094_p4.read());
}

void cordic::thread_tmp_82_fu_1108_p4() {
    tmp_82_fu_1108_p4 = mt_s_fu_1088_p2.read().range(12, 10);
}

void cordic::thread_tmp_83_fu_1118_p3() {
    tmp_83_fu_1118_p3 = (!tmp_79_reg_1244.read()[0].is_01())? sc_lv<3>(): ((tmp_79_reg_1244.read()[0].to_bool())? tmp_82_fu_1108_p4.read(): tmp_81_fu_1104_p1.read());
}

void cordic::thread_tmp_84_fu_1139_p4() {
    tmp_84_fu_1139_p4 = p_Val2_7_9_fu_1079_p2.read().range(11, 10);
}

void cordic::thread_tmp_85_fu_1149_p1() {
    tmp_85_fu_1149_p1 = esl_sext<3,2>(tmp_84_fu_1139_p4.read());
}

void cordic::thread_tmp_86_fu_1153_p4() {
    tmp_86_fu_1153_p4 = mt7_s_fu_1133_p2.read().range(12, 10);
}

void cordic::thread_tmp_87_fu_1163_p3() {
    tmp_87_fu_1163_p3 = (!tmp_79_reg_1244.read()[0].is_01())? sc_lv<3>(): ((tmp_79_reg_1244.read()[0].to_bool())? tmp_86_fu_1153_p4.read(): tmp_85_fu_1149_p1.read());
}

void cordic::thread_tmp_8_fu_296_p4() {
    tmp_8_fu_296_p4 = p_Val2_7_1_fu_210_p2.read().range(10, 2);
}

void cordic::thread_tmp_9_fu_314_p1() {
    tmp_9_fu_314_p1 = esl_sext<12,9>(tmp_10_fu_306_p3.read());
}

void cordic::thread_tmp_fu_244_p4() {
    tmp_fu_244_p4 = p_Val2_4_1_fu_200_p2.read().range(9, 2);
}

void cordic::thread_tmp_s_fu_473_p1() {
    tmp_s_fu_473_p1 = esl_sext<12,9>(tmp_16_v_fu_466_p3.read());
}

void cordic::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

void cordic::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"theta_V\" :  \"" << theta_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_V\" :  \"" << s_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_V_ap_vld\" :  \"" << s_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_V\" :  \"" << c_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_V_ap_vld\" :  \"" << c_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

