// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "loop_functions.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic loop_functions::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic loop_functions::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> loop_functions::ap_ST_fsm_state1 = "1";
const sc_lv<2> loop_functions::ap_ST_fsm_state2 = "10";
const sc_lv<32> loop_functions::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> loop_functions::ap_const_lv32_1 = "1";
const bool loop_functions::ap_const_boolean_0 = false;
const bool loop_functions::ap_const_boolean_1 = true;

loop_functions::loop_functions(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_sub_func_fu_34 = new sub_func("grp_sub_func_fu_34");
    grp_sub_func_fu_34->ap_clk(ap_clk);
    grp_sub_func_fu_34->ap_rst(ap_rst);
    grp_sub_func_fu_34->ap_start(grp_sub_func_fu_34_ap_start);
    grp_sub_func_fu_34->ap_done(grp_sub_func_fu_34_ap_done);
    grp_sub_func_fu_34->ap_idle(grp_sub_func_fu_34_ap_idle);
    grp_sub_func_fu_34->ap_ready(grp_sub_func_fu_34_ap_ready);
    grp_sub_func_fu_34->I_address0(grp_sub_func_fu_34_I_address0);
    grp_sub_func_fu_34->I_ce0(grp_sub_func_fu_34_I_ce0);
    grp_sub_func_fu_34->I_q0(A_q0);
    grp_sub_func_fu_34->O_address0(grp_sub_func_fu_34_O_address0);
    grp_sub_func_fu_34->O_ce0(grp_sub_func_fu_34_O_ce0);
    grp_sub_func_fu_34->O_we0(grp_sub_func_fu_34_O_we0);
    grp_sub_func_fu_34->O_d0(grp_sub_func_fu_34_O_d0);
    grp_sub_func_fu_34->limit(xlimit);
    grp_sub_func_fu_44 = new sub_func("grp_sub_func_fu_44");
    grp_sub_func_fu_44->ap_clk(ap_clk);
    grp_sub_func_fu_44->ap_rst(ap_rst);
    grp_sub_func_fu_44->ap_start(grp_sub_func_fu_44_ap_start);
    grp_sub_func_fu_44->ap_done(grp_sub_func_fu_44_ap_done);
    grp_sub_func_fu_44->ap_idle(grp_sub_func_fu_44_ap_idle);
    grp_sub_func_fu_44->ap_ready(grp_sub_func_fu_44_ap_ready);
    grp_sub_func_fu_44->I_address0(grp_sub_func_fu_44_I_address0);
    grp_sub_func_fu_44->I_ce0(grp_sub_func_fu_44_I_ce0);
    grp_sub_func_fu_44->I_q0(B_q0);
    grp_sub_func_fu_44->O_address0(grp_sub_func_fu_44_O_address0);
    grp_sub_func_fu_44->O_ce0(grp_sub_func_fu_44_O_ce0);
    grp_sub_func_fu_44->O_we0(grp_sub_func_fu_44_O_we0);
    grp_sub_func_fu_44->O_d0(grp_sub_func_fu_44_O_d0);
    grp_sub_func_fu_44->limit(ylimit);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( grp_sub_func_fu_34_I_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( grp_sub_func_fu_34_I_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_B_address0);
    sensitive << ( grp_sub_func_fu_44_I_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( grp_sub_func_fu_44_I_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_X_address0);
    sensitive << ( grp_sub_func_fu_34_O_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_X_ce0);
    sensitive << ( grp_sub_func_fu_34_O_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_X_d0);
    sensitive << ( grp_sub_func_fu_34_O_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_X_we0);
    sensitive << ( grp_sub_func_fu_34_O_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Y_address0);
    sensitive << ( grp_sub_func_fu_44_O_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Y_ce0);
    sensitive << ( grp_sub_func_fu_44_O_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Y_d0);
    sensitive << ( grp_sub_func_fu_44_O_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_Y_we0);
    sensitive << ( grp_sub_func_fu_44_O_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state2_on_subcall_done);
    sensitive << ( grp_sub_func_fu_34_ap_done );
    sensitive << ( grp_sub_func_fu_44_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_METHOD(thread_grp_sub_func_fu_34_ap_start);
    sensitive << ( ap_reg_grp_sub_func_fu_34_ap_start );

    SC_METHOD(thread_grp_sub_func_fu_44_ap_start);
    sensitive << ( ap_reg_grp_sub_func_fu_44_ap_start );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_state2_on_subcall_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "01";
    ap_reg_grp_sub_func_fu_34_ap_start = SC_LOGIC_0;
    ap_reg_grp_sub_func_fu_44_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "loop_functions_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, X_address0, "(port)X_address0");
    sc_trace(mVcdFile, X_ce0, "(port)X_ce0");
    sc_trace(mVcdFile, X_we0, "(port)X_we0");
    sc_trace(mVcdFile, X_d0, "(port)X_d0");
    sc_trace(mVcdFile, Y_address0, "(port)Y_address0");
    sc_trace(mVcdFile, Y_ce0, "(port)Y_ce0");
    sc_trace(mVcdFile, Y_we0, "(port)Y_we0");
    sc_trace(mVcdFile, Y_d0, "(port)Y_d0");
    sc_trace(mVcdFile, xlimit, "(port)xlimit");
    sc_trace(mVcdFile, ylimit, "(port)ylimit");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_sub_func_fu_34_ap_start, "grp_sub_func_fu_34_ap_start");
    sc_trace(mVcdFile, grp_sub_func_fu_34_ap_done, "grp_sub_func_fu_34_ap_done");
    sc_trace(mVcdFile, grp_sub_func_fu_34_ap_idle, "grp_sub_func_fu_34_ap_idle");
    sc_trace(mVcdFile, grp_sub_func_fu_34_ap_ready, "grp_sub_func_fu_34_ap_ready");
    sc_trace(mVcdFile, grp_sub_func_fu_34_I_address0, "grp_sub_func_fu_34_I_address0");
    sc_trace(mVcdFile, grp_sub_func_fu_34_I_ce0, "grp_sub_func_fu_34_I_ce0");
    sc_trace(mVcdFile, grp_sub_func_fu_34_O_address0, "grp_sub_func_fu_34_O_address0");
    sc_trace(mVcdFile, grp_sub_func_fu_34_O_ce0, "grp_sub_func_fu_34_O_ce0");
    sc_trace(mVcdFile, grp_sub_func_fu_34_O_we0, "grp_sub_func_fu_34_O_we0");
    sc_trace(mVcdFile, grp_sub_func_fu_34_O_d0, "grp_sub_func_fu_34_O_d0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_ap_start, "grp_sub_func_fu_44_ap_start");
    sc_trace(mVcdFile, grp_sub_func_fu_44_ap_done, "grp_sub_func_fu_44_ap_done");
    sc_trace(mVcdFile, grp_sub_func_fu_44_ap_idle, "grp_sub_func_fu_44_ap_idle");
    sc_trace(mVcdFile, grp_sub_func_fu_44_ap_ready, "grp_sub_func_fu_44_ap_ready");
    sc_trace(mVcdFile, grp_sub_func_fu_44_I_address0, "grp_sub_func_fu_44_I_address0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_I_ce0, "grp_sub_func_fu_44_I_ce0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_O_address0, "grp_sub_func_fu_44_O_address0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_O_ce0, "grp_sub_func_fu_44_O_ce0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_O_we0, "grp_sub_func_fu_44_O_we0");
    sc_trace(mVcdFile, grp_sub_func_fu_44_O_d0, "grp_sub_func_fu_44_O_d0");
    sc_trace(mVcdFile, ap_reg_grp_sub_func_fu_34_ap_start, "ap_reg_grp_sub_func_fu_34_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_reg_grp_sub_func_fu_44_ap_start, "ap_reg_grp_sub_func_fu_44_ap_start");
    sc_trace(mVcdFile, ap_block_state2_on_subcall_done, "ap_block_state2_on_subcall_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("loop_functions.hdltvin.dat");
    mHdltvoutHandle.open("loop_functions.hdltvout.dat");
}

loop_functions::~loop_functions() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_sub_func_fu_34;
    delete grp_sub_func_fu_44;
}

void loop_functions::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_sub_func_fu_34_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_reg_grp_sub_func_fu_34_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sub_func_fu_34_ap_ready.read())) {
            ap_reg_grp_sub_func_fu_34_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_sub_func_fu_44_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_reg_grp_sub_func_fu_44_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sub_func_fu_44_ap_ready.read())) {
            ap_reg_grp_sub_func_fu_44_ap_start = ap_const_logic_0;
        }
    }
}

void loop_functions::thread_A_address0() {
    A_address0 = grp_sub_func_fu_34_I_address0.read();
}

void loop_functions::thread_A_ce0() {
    A_ce0 = grp_sub_func_fu_34_I_ce0.read();
}

void loop_functions::thread_B_address0() {
    B_address0 = grp_sub_func_fu_44_I_address0.read();
}

void loop_functions::thread_B_ce0() {
    B_ce0 = grp_sub_func_fu_44_I_ce0.read();
}

void loop_functions::thread_X_address0() {
    X_address0 = grp_sub_func_fu_34_O_address0.read();
}

void loop_functions::thread_X_ce0() {
    X_ce0 = grp_sub_func_fu_34_O_ce0.read();
}

void loop_functions::thread_X_d0() {
    X_d0 = grp_sub_func_fu_34_O_d0.read();
}

void loop_functions::thread_X_we0() {
    X_we0 = grp_sub_func_fu_34_O_we0.read();
}

void loop_functions::thread_Y_address0() {
    Y_address0 = grp_sub_func_fu_44_O_address0.read();
}

void loop_functions::thread_Y_ce0() {
    Y_ce0 = grp_sub_func_fu_44_O_ce0.read();
}

void loop_functions::thread_Y_d0() {
    Y_d0 = grp_sub_func_fu_44_O_d0.read();
}

void loop_functions::thread_Y_we0() {
    Y_we0 = grp_sub_func_fu_44_O_we0.read();
}

void loop_functions::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void loop_functions::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void loop_functions::thread_ap_block_state2_on_subcall_done() {
    ap_block_state2_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_sub_func_fu_34_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_sub_func_fu_44_ap_done.read()));
}

void loop_functions::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void loop_functions::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void loop_functions::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void loop_functions::thread_grp_sub_func_fu_34_ap_start() {
    grp_sub_func_fu_34_ap_start = ap_reg_grp_sub_func_fu_34_ap_start.read();
}

void loop_functions::thread_grp_sub_func_fu_44_ap_start() {
    grp_sub_func_fu_44_ap_start = ap_reg_grp_sub_func_fu_44_ap_start.read();
}

void loop_functions::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_block_state2_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

void loop_functions::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_address0\" :  \"" << A_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"A_ce0\" :  \"" << A_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"A_q0\" :  \"" << A_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_address0\" :  \"" << B_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"B_ce0\" :  \"" << B_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"B_q0\" :  \"" << B_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_address0\" :  \"" << X_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_ce0\" :  \"" << X_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_we0\" :  \"" << X_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"X_d0\" :  \"" << X_d0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Y_address0\" :  \"" << Y_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Y_ce0\" :  \"" << Y_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Y_we0\" :  \"" << Y_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"Y_d0\" :  \"" << Y_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"xlimit\" :  \"" << xlimit.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ylimit\" :  \"" << ylimit.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

